// Corporate late game: valuation, optional IPO, and public-market consequences without stock trading.

const PUBLIC_RIVAL_IDS=['R1','R2','R5'];
function ensureCorporateState(st=state){
 st.corporateState=st.corporateState||{status:'private',founderOwnership:100,investorConfidence:62,ipoDeclinedUntil:0,ipoWeek:null,ipoProceeds:0,lastReviewWeek:0,lastOfferWeek:0,lastFundamental:null,lastMarketCap:null,lastSharePrice:null,history:[],quarterly:[],boardPressure:false};
 const c=st.corporateState;c.history=c.history||[];c.quarterly=c.quarterly||[];
 if(c.status===undefined)c.status='private';if(c.founderOwnership===undefined)c.founderOwnership=c.status==='public'?75:100;if(c.investorConfidence===undefined)c.investorConfidence=62;
 if(c.ipoDeclinedUntil===undefined)c.ipoDeclinedUntil=0;if(c.lastReviewWeek===undefined)c.lastReviewWeek=0;if(c.lastOfferWeek===undefined)c.lastOfferWeek=0;if(c.boardPressure===undefined)c.boardPressure=false;
 return c;
}
function publicCompanyWeeklyOverhead(st=state){return ensureCorporateState(st).status==='public'?.055:0}
function corporateWeeklyOverhead(st=state){return publicCompanyWeeklyOverhead(st)+(typeof ownedStreamingWeeklyOverhead==='function'?ownedStreamingWeeklyOverhead(st):0)}
function corporateTrailingFilms(st=state,weeks=52){return (st.films||[]).filter(f=>f.owner==='player'&&f.stage==='complete'&&(f.completeWeek||0)>=(st.week-weeks+1))}
function corporateFundamentals(st=state){
 const c=ensureCorporateState(st),g=ensureStudioGrowth(st),done=(st.films||[]).filter(f=>f.owner==='player'&&f.stage==='complete'),recent=corporateTrailingFilms(st,52);
 const profit=recent.reduce((s,f)=>s+studioFilmProfit(f),0),library=done.reduce((s,f)=>s+(ensureAfterlifeState(f)?.libraryValue||0),0),awards=done.reduce((s,f)=>s+(ensureAfterlifeState(f)?.wins?.length||0),0);
 const strongIP=done.filter(f=>(f.finalGross||0)>=120&&(f.review?.audience||0)>=78).length,recognition=g.recognition||12,fans=g.fans||.04,debt=st.finance?.bridgeDebt||0,financial=st.reputation?.financial||50;
 const streamingAsset=typeof ownedStreamingAssetValue==='function'?ownedStreamingAssetValue(st):0,capitalAssets=capitalAssetValue(st);
 const value=clamp(25+Math.max(0,st.cash||0)*.9+library*1.8+Math.max(-25,profit)*2.8+recognition*.9+Math.sqrt(Math.max(0,fans))*9+awards*2.5+strongIP*5+(financial-50)*.45-debt*1.4+streamingAsset+capitalAssets,25,1500);
 return {value:+value.toFixed(1),profit:+profit.toFixed(1),library:+library.toFixed(1),streamingAsset:+streamingAsset.toFixed(1),capitalAssets:+capitalAssets.toFixed(1),awards,strongIP,recognition:+recognition.toFixed(1),fans:+fans.toFixed(2),debt:+debt.toFixed(1),released:done.length,recentReleases:recent.length};
}
function corporateMarketSnapshot(st=state){
 const c=ensureCorporateState(st),f=corporateFundamentals(st),mult=c.status==='public'?(.78+clamp(c.investorConfidence,15,90)/100*.44):1,cap=+(f.value*mult).toFixed(1),price=+(cap/5).toFixed(2);
 return {...f,status:c.status,marketCap:cap,sharePrice:price,confidence:Math.round(c.investorConfidence),founderOwnership:+c.founderOwnership.toFixed(1)};
}
function corporateVisible(){const c=ensureCorporateState(),g=ensureStudioGrowth();return !!state.studio&&state.careerStarted&&(c.status==='public'||state.week>=105||(g.recognition||0)>=52)}
function ipoEligibility(){
 const c=ensureCorporateState(),f=corporateFundamentals(),reasons=[];
 if(c.status==='public')reasons.push('The studio is already publicly traded.');
 if(state.week<156)reasons.push('Build at least three full years of operating history.');
 if(f.recognition<72)reasons.push('Reach 72 Studio Recognition.');
 if(f.released<6)reasons.push('Release at least six films.');
 if(f.value<150)reasons.push('Build an estimated studio valuation of at least $150m.');
 if((state.reputation?.financial||0)<55)reasons.push('Reach 55 Financial Reputation.');
 if(f.debt>15)reasons.push('Reduce bridge debt below $15m.');
 if((c.ipoDeclinedUntil||0)>state.week)reasons.push(`The studio chose to remain private until at least Week ${c.ipoDeclinedUntil}.`);
 return {ok:reasons.length===0,reasons,fundamentals:f};
}
function estimatedIPOProceeds(){const f=corporateFundamentals();return +clamp(f.value*.23,35,150).toFixed(1)}
function pendingIPODeskItem(){return ensureDesk().items.find(x=>!x.resolved&&x.templateId==='corporate-ipo')||null}
function maybeOfferIPO(){
 if(!state.studio||!state.careerStarted||state.week%13!==0)return false;
 const c=ensureCorporateState(),e=ipoEligibility();if(!e.ok||pendingIPODeskItem()||state.week-(c.lastOfferWeek||0)<39)return false;
 const proceeds=estimatedIPOProceeds();c.lastOfferWeek=state.week;
 pushDeskItem({templateId:'corporate-ipo',repeatKey:`corporate-ipo:${Math.ceil(state.week/52)}`,family:'corporate',type:'finance',source:'Corporate Finance',urgency:'action',requiresAction:true,expiresWeek:state.week+8,subject:state.studio.name,headline:`Bankers believe ${state.studio.name} is ready for an IPO`,body:`Advisers estimate the studio at roughly ${money(e.fundamentals.value)}. Selling a 25% public stake could raise about ${money(proceeds)} after flotation costs. You would retain 75% founder control, but public-market reporting adds ${moneyFine(.055)} a week in permanent overhead and results will begin affecting investor confidence and the studio's quoted value.`,choices:[['ipo','Take the studio public'],['private','Remain independent']]});
 return true;
}
function resolveCorporateDeskChoice(item,key){
 if(item?.templateId==='streaming-feasibility'&&typeof resolveOwnedStreamingDeskChoice==='function')return resolveOwnedStreamingDeskChoice(item,key);
 if(item?.templateId!=='corporate-ipo')return null;
 const c=ensureCorporateState();
 if(key==='private'){
  c.ipoDeclinedUntil=state.week+52;c.history.unshift({week:state.week,type:'private',text:'Chose to remain privately controlled.'});
  return `${state.studio.name} stays private. No outside shareholders enter the company, and the studio keeps complete ownership control. Bankers will leave the question alone for roughly another year.`;
 }
 if(key==='ipo'){
  if(c.status==='public')return `${state.studio.name} is already publicly traded.`;
  const proceeds=estimatedIPOProceeds(),f=corporateFundamentals();
  state.cash+=proceeds;c.status='public';c.founderOwnership=75;c.ipoWeek=state.week;c.ipoProceeds=proceeds;c.investorConfidence=62;c.lastFundamental=f.value;c.lastReviewWeek=state.week;c.lastMarketCap=corporateMarketSnapshot().marketCap;c.lastSharePrice=corporateMarketSnapshot().sharePrice;c.boardPressure=false;
  c.history.unshift({week:state.week,type:'ipo',proceeds,valuation:f.value,text:`IPO completed at an estimated ${money(f.value)} valuation.`});
  state.reputation.financial=clamp((state.reputation.financial||50)+3,15,95);
  addNews(state,`${state.studio.name} has gone public, raising approximately ${money(proceeds)} while the founder retains a 75% controlling stake.`,'Trade Finance');
  queueStudioMoment(null,'studioIPO',{kicker:'THE STUDIO GOES PUBLIC',title:`${state.studio.name} rings the opening bell`,tone:'great',result:`${money(proceeds)} RAISED`,summary:`The company has crossed from founder-owned studio to public corporation. The new capital creates room to expand, but every hit, flop and debt decision now has a visible market consequence.`,stats:[['IPO proceeds',money(proceeds)],['Founder control','75%'],['Opening valuation',money(f.value)],['New fixed cost',`${moneyFine(.055)}/week`]],sections:[{title:'What changes',text:'Film quality and box office still determine the underlying business. Public investors do not improve the movies; they simply react to the results and the way the company uses its capital.'},{title:'What does not change',text:'There is still no Game Over. A collapsing share price is a career story and a financial constraint, not an automatic end state. Strong films and disciplined finances can rebuild confidence.'}]});
  return `${state.studio.name} completes its IPO and raises ${money(proceeds)}. Founder ownership remains at 75%, while the company now carries public-market scrutiny and additional reporting overhead.`;
 }
 return null;
}
function corporateOutcomeBand(f){const p=studioFilmProfit(f);if(f.releaseProfile?.type==='bomb'||p<=-10)return 'bomb';if(p>=14||f.releaseProfile?.type==='breakout')return 'hit';return 'middle'}
function reviewPublicCompanyQuarter(){
 const c=ensureCorporateState();if(c.status!=='public'||state.week%13!==0||state.week===c.lastReviewWeek)return false;
 const before=corporateMarketSnapshot(),prevFund=c.lastFundamental||before.value,prevConf=c.investorConfidence,prevCap=c.lastMarketCap||before.marketCap;
 const recent=corporateTrailingFilms(state,13),hits=recent.filter(f=>corporateOutcomeBand(f)==='hit').length,bombs=recent.filter(f=>corporateOutcomeBand(f)==='bomb').length;
 const f=corporateFundamentals(),fundMove=(f.value-prevFund)/Math.max(1,prevFund),recognitionMove=f.recognition-(c.lastRecognition??f.recognition),debtPenalty=f.debt>20?5:f.debt>10?2:0;
 const streamingSignal=typeof ownedStreamingInvestorSignal==='function'?ownedStreamingInvestorSignal():0;
 let delta=clamp(fundMove*28+hits*3-bombs*5+recognitionMove*.6-debtPenalty+streamingSignal,-12,12);
 if(!recent.length&&corporateTrailingFilms(state,39).length===0)delta-=2;
 c.investorConfidence=clamp(c.investorConfidence+delta,15,90);c.lastReviewWeek=state.week;c.lastFundamental=f.value;c.lastRecognition=f.recognition;
 const after=corporateMarketSnapshot(),capMove=(after.marketCap-prevCap)/Math.max(1,prevCap);const pressureBefore=!!c.boardPressure;c.boardPressure=c.investorConfidence<35;c.lastMarketCap=after.marketCap;c.lastSharePrice=after.sharePrice;
 const q={week:state.week,confidence:Math.round(c.investorConfidence),delta:+delta.toFixed(1),marketCap:after.marketCap,sharePrice:after.sharePrice,hits,bombs,fundamental:f.value,capMove:+(capMove*100).toFixed(1)};c.quarterly.unshift(q);c.quarterly=c.quarterly.slice(0,24);c.history.unshift({week:state.week,type:'quarter',...q});c.history=c.history.slice(0,80);
 if(Math.abs(delta)>=4||pressureBefore!==c.boardPressure||Math.abs(capMove)>=.12){
  const direction=delta>=0?'strengthened':'weakened',tone=c.boardPressure?'Board pressure is now intense. ':'';
  pushDeskItem({templateId:'corporate-quarter',repeatKey:`corporate-quarter:${state.week}`,family:'corporate',type:'finance',source:'Market Desk',urgency:c.boardPressure?'urgent':'normal',requiresAction:false,headline:`Investor confidence ${direction} after the latest quarter`,body:`${tone}Confidence is ${Math.round(c.investorConfidence)}/100 and the studio's market value is about ${money(after.marketCap)} (${capMove>=0?'+':''}${(capMove*100).toFixed(1)}% since the prior review). ${hits?`${hits} clear hit${hits===1?'':'s'} helped. `:''}${bombs?`${bombs} major miss${bombs===1?'':'es'} weighed on the company. `:''}${f.debt>10?`Bridge debt of ${money(f.debt)} remains a concern.`:''}`,choices:[],resolved:true,read:false,expanded:false});
 }
 return true;
}
function processCorporateWeek(){
 ensureCorporateState();if(state.week%13===0){if(typeof processOwnedStreamingQuarter==='function')processOwnedStreamingQuarter();reviewPublicCompanyQuarter();maybeOfferIPO();if(typeof maybeSurfaceOwnedStreamingOpportunity==='function')maybeSurfaceOwnedStreamingOpportunity();const c=ensureCorporateState(),s=corporateMarketSnapshot();if(c.status==='private'){c.lastFundamental=s.value;c.lastMarketCap=s.marketCap;c.lastSharePrice=s.sharePrice} }
}
function rivalCorporateSnapshot(rv){
 const done=state.films.filter(f=>f.owner===rv.id&&f.stage==='complete'),recent=done.filter(f=>state.week-(f.completeWeek||0)<=52),profit=recent.reduce((s,f)=>s+(f.estimatedProfit||0),0),recognition=rv.recognition??rv.reputation??50,fans=rv.fans||.5,debt=rv.debt||0;
 const cap=clamp(35+(rv.cash||0)*.65+recognition*1.35+Math.sqrt(Math.max(0,fans))*10+profit*2.1-debt*1.2,35,1100),sentiment=clamp(52+profit*.45+(recognition-55)*.25-debt*.35,22,86),price=cap/5;
 return {id:rv.id,name:rv.name,head:rv.head?.name||'Studio leadership',marketCap:+cap.toFixed(1),sharePrice:+price.toFixed(2),sentiment:Math.round(sentiment),profit:+profit.toFixed(1)};
}
function publicRivalMarket(){return state.rivals.filter(rv=>PUBLIC_RIVAL_IDS.includes(rv.id)).map(rivalCorporateSnapshot).sort((a,b)=>b.marketCap-a.marketCap)}
function investorConfidenceLabel(v){return v>=78?'Strong support':v>=62?'Constructive':v>=48?'Watchful':v>=35?'Under pressure':'Boardroom alarm'}
function studioCorporateBody(){
 const c=ensureCorporateState(),s=corporateMarketSnapshot(),elig=ipoEligibility(),publicCo=c.status==='public',quarters=c.quarterly||[],rivals=publicRivalMarket();
 return `<div class="legacy-hero"><div><div class="badge">${publicCo?'PUBLIC COMPANY':'PRIVATE COMPANY'}</div><div class="legacy-score">${money(publicCo?s.marketCap:s.value)}</div><div class="legacy-label">${publicCo?'market value':'estimated studio value'}</div><div class="body">${publicCo?`The studio is publicly traded. You still control ${s.founderOwnership.toFixed(0)}%, but investors now react to films, debt and how effectively the company converts scale into results.`:`The studio remains founder controlled. Valuation is an industry estimate based on cash, catalogue, recent results, recognition and debt — not spendable money.`}</div></div><div class="legacy-count"><strong>${publicCo?s.confidence+'%':s.released}</strong><span>${publicCo?'investor confidence':'released films'}</span><strong style="margin-top:10px">${publicCo?`$${s.sharePrice.toFixed(2)}`:Math.round(s.recognition)}</strong><span>${publicCo?'indicative share price':'recognition'}</span></div></div>
 <div class="grid cols4" style="margin-top:14px"><div class="card"><div class="badge">Recent film P/L</div><div class="kpi ${s.profit>=0?'goodtext':'badtext'}">${s.profit>=0?'+':''}${money(s.profit)}</div><div class="small">trailing 52 weeks</div></div><div class="card"><div class="badge">Catalogue value</div><div class="kpi">${money(s.library)}</div></div><div class="card"><div class="badge">Bridge debt</div><div class="kpi ${s.debt>10?'badtext':''}">${money(s.debt)}</div></div><div class="card"><div class="badge">Founder control</div><div class="kpi">${s.founderOwnership.toFixed(0)}%</div></div></div>
 ${typeof ownedStreamingCorporatePanel==='function'?ownedStreamingCorporatePanel():''}
  ${capitalAssetsCorporatePanel()}
 ${publicCo?`<div class="section-title"><h2>Public-market pressure</h2><span class="pill ${c.boardPressure?'bad':s.confidence>=62?'good':'warn'}">${investorConfidenceLabel(s.confidence)}</span></div><div class="card ${c.boardPressure?'dangerline':''}"><div class="body">${c.boardPressure?'The company has entered a period of serious board and investor pressure. There is no forced sale or Game Over, but another run of expensive misses will keep depressing the company’s value.':'Investors are judging the company on underlying value, recent film results, recognition and balance-sheet discipline rather than demanding a film every quarter.'}</div><div class="listrow"><span>Investor confidence</span><strong>${s.confidence}/100</strong></div><div class="listrow"><span>Market capitalisation</span><strong>${money(s.marketCap)}</strong></div><div class="listrow"><span>Indicative share price</span><strong>$${s.sharePrice.toFixed(2)}</strong></div><div class="listrow"><span>Public-company overhead</span><strong>${moneyFine(publicCompanyWeeklyOverhead())}/week</strong></div></div>`:`<div class="section-title"><h2>IPO readiness</h2><span class="small">Outside capital is optional</span></div><div class="card ${elig.ok?'goodline':''}">${elig.ok?`<div class="body"><strong>The studio is IPO-ready.</strong> Advisers can raise roughly ${money(estimatedIPOProceeds())} by selling a 25% public stake. A formal proposal appears through the Studio Desk at a quarterly review.</div>`:`<div class="body">The studio is not yet in a clean position to float. Remaining private carries no penalty.</div><div style="margin-top:8px">${elig.reasons.map(x=>`<div class="small">• ${x}</div>`).join('')}</div>`}</div>`}
 ${quarters.length?`<div class="section-title"><h2>Quarterly market history</h2><span class="small">Public-company reactions, not player objectives</span></div><div class="card">${quarters.slice(0,8).map(q=>`<div class="listrow"><div><strong>Week ${q.week}</strong><div class="small">Confidence ${q.delta>=0?'+':''}${q.delta} · ${q.hits} hit${q.hits===1?'':'s'} · ${q.bombs} major miss${q.bombs===1?'':'es'}</div></div><div style="text-align:right"><strong>$${q.sharePrice.toFixed(2)}</strong><div class="small">${q.capMove>=0?'+':''}${q.capMove}% value</div></div></div>`).join('')}</div>`:''}
 <div class="section-title"><h2>Public studio board</h2><span class="small">Context only — Project Slate is not a stock-trading game</span></div><div class="grid cols2">${rivals.map(x=>`<div class="card"><div class="row"><div><strong>${x.name}</strong><div class="small">${x.head}</div></div><strong>$${x.sharePrice.toFixed(2)}</strong></div><div class="listrow"><span>Market value</span><strong>${money(x.marketCap)}</strong></div><div class="listrow"><span>Market tone</span><strong>${x.sentiment>=68?'Positive':x.sentiment<42?'Under pressure':'Watchful'}</strong></div></div>`).join('')}</div>`;
}
// Studio-owned streaming platform: a late-career corporate expansion with real carrying costs.

const OWNED_STREAMING_MODELS={
 broad:{id:'broad',label:'Broad subscription service',short:'Broad',launchCost:78,fixedOverhead:.25,perSubscriberOverhead:.075,weeklyRevenuePerM:.205,initialMult:1.00,churn:.040,releaseMult:1.00,desc:'Balanced mass-market service built around the whole studio library. Moderate launch cost, moderate churn and the widest content appetite.'},
 prestige:{id:'prestige',label:'Curated prestige service',short:'Prestige',launchCost:62,fixedOverhead:.19,perSubscriberOverhead:.070,weeklyRevenuePerM:.190,initialMult:.78,churn:.026,releaseMult:.82,desc:'Smaller audience ceiling but lower fixed costs and better retention when acclaimed films keep the service culturally relevant.'},
 event:{id:'event',label:'Event-driven service',short:'Event',launchCost:92,fixedOverhead:.34,perSubscriberOverhead:.085,weeklyRevenuePerM:.220,initialMult:1.16,churn:.058,releaseMult:1.28,desc:'Built around major premieres and franchise-scale titles. Subscriber spikes can be large, but the audience leaves quickly when the pipeline goes quiet.'}
};
function ownedStreamingModel(id){return OWNED_STREAMING_MODELS[id]||null}
function defaultOwnedStreamingState(){return {status:'none',name:null,model:null,launchWeek:null,launchCost:0,subscribers:0,peakSubscribers:0,lastQuarterSubscribers:0,lastQuarterWeek:0,exclusiveFilmIds:[],history:[],quarterly:[],lifetimeRevenue:0,lifetimeOperatingCost:0,currentQuarterRevenue:0,currentQuarterCost:0,lastWeeklyRevenue:0,lastWeeklyCost:0,lastWeeklyNet:0,lastExclusiveWeek:null,notifiedWeek:0,declinedUntil:0,woundDownWeek:null}}
function ensureOwnedStreamingState(st=state){const c=ensureCorporateState(st);c.streamingPlatform=c.streamingPlatform||defaultOwnedStreamingState();const p=c.streamingPlatform,base=defaultOwnedStreamingState();Object.keys(base).forEach(k=>{if(p[k]===undefined)p[k]=deep(base[k])});p.exclusiveFilmIds=p.exclusiveFilmIds||[];p.history=p.history||[];p.quarterly=p.quarterly||[];return p}
function ownedStreamingPlatformName(){const raw=String(state.studio?.name||'Studio').replace(/\b(studios?|pictures?|films?|entertainment|productions?)\b/ig,'').replace(/\s{2,}/g,' ').trim();return `${raw||state.studio?.name||'Studio'}+`}
function ownedStreamingWeeklyOverhead(st=state){const p=ensureOwnedStreamingState(st);if(p.status!=='active')return 0;const m=ownedStreamingModel(p.model);return m?+(m.fixedOverhead+p.subscribers*m.perSubscriberOverhead).toFixed(4):0}
function ownedStreamingWeeklyRevenue(st=state){const p=ensureOwnedStreamingState(st);if(p.status!=='active')return 0;const m=ownedStreamingModel(p.model);return m?+(p.subscribers*m.weeklyRevenuePerM).toFixed(4):0}
function ownedStreamingWeeklyNet(st=state){return +(ownedStreamingWeeklyRevenue(st)-ownedStreamingWeeklyOverhead(st)).toFixed(4)}
function ownedStreamingAssetValue(st=state){const p=ensureOwnedStreamingState(st);if(p.status!=='active')return 0;const net=ownedStreamingWeeklyNet(st),depth=(p.exclusiveFilmIds||[]).length;return +clamp(p.subscribers*18+depth*1.6+Math.max(0,net)*52*4-Math.max(0,-net)*52*1.5,0,320).toFixed(1)}
function ownedStreamingLaunchEligibility(){
 const p=ensureOwnedStreamingState(),f=corporateFundamentals(),reasons=[];
 if(p.status==='active')reasons.push(`${p.name||'The platform'} is already operating.`);
 if(p.status==='wound_down')reasons.push('The studio has already exited direct-to-consumer streaming in this career.');
 if(state.week<208)reasons.push('Build at least four full years of operating history.');
 if(f.recognition<80)reasons.push('Reach 80 Studio Recognition.');
 if(f.released<10)reasons.push('Release at least ten films.');
 if(f.library<25)reasons.push('Build at least $25m of catalogue value.');
 if(f.value<250)reasons.push('Build an estimated studio valuation of at least $250m.');
 if(f.debt>10)reasons.push('Reduce bridge debt below $10m.');
 if(state.cash<62)reasons.push('Hold at least $62m cash to fund the smallest credible launch.');
 if((p.declinedUntil||0)>state.week)reasons.push(`The board shelved the proposal until at least Week ${p.declinedUntil}.`);
 return {ok:reasons.length===0,reasons,fundamentals:f};
}
function ownedStreamingAvailableFilms(){return playerFilms().filter(f=>f.stage==='complete'&&!ensureStreamingState(f).activeDeal&&!ensureStreamingState(f).ownedPlatform)}
function ownedStreamingSeedLibrary(){const p=ensureOwnedStreamingState();const picks=ownedStreamingAvailableFilms().sort((a,b)=>afterlifeStrength(b)-afterlifeStrength(a)).slice(0,4);picks.forEach(f=>assignFilmToOwnedPlatform(f,true));return picks}
function initialOwnedStreamingSubscribers(model){const f=corporateFundamentals(),m=ownedStreamingModel(model),base=.25+Math.sqrt(Math.max(0,f.fans||0))*.18+f.library*.012+f.recognition*.006+f.released*.025;return +clamp(base*(m?.initialMult||1),.30,4.8).toFixed(2)}
function launchOwnedStreamingPlatform(modelId){
 const p=ensureOwnedStreamingState(),m=ownedStreamingModel(modelId),e=ownedStreamingLaunchEligibility();if(!m)return showToast('Choose a streaming model.');if(!e.ok)return showToast(e.reasons[0]||'The studio is not ready to launch a platform.');if(state.cash<m.launchCost)return showToast(`You need ${money(m.launchCost)} in cash to launch this model.`);
 state.cash-=m.launchCost;p.status='active';p.name=ownedStreamingPlatformName();p.model=m.id;p.launchWeek=state.week;p.launchCost=m.launchCost;p.subscribers=initialOwnedStreamingSubscribers(m.id);p.peakSubscribers=p.subscribers;p.lastQuarterSubscribers=p.subscribers;p.lastQuarterWeek=state.week;p.exclusiveFilmIds=[];p.lifetimeRevenue=0;p.lifetimeOperatingCost=0;p.currentQuarterRevenue=0;p.currentQuarterCost=0;p.lastWeeklyRevenue=0;p.lastWeeklyCost=ownedStreamingWeeklyOverhead();p.lastWeeklyNet=-p.lastWeeklyCost;p.lastExclusiveWeek=state.week;p.history.unshift({week:state.week,type:'launch',model:m.id,subscribers:p.subscribers,cost:m.launchCost});
 const seeded=ownedStreamingSeedLibrary();p.lastExclusiveWeek=state.week;
 addNews(state,`${state.studio.name} has launched ${p.name}, a ${m.label.toLowerCase()} with ${p.subscribers.toFixed(2)}m opening subscribers and ${seeded.length} catalogue anchors.`,'Trade Finance');
 if(ensureCorporateState().status==='public')ensureCorporateState().investorConfidence=clamp(ensureCorporateState().investorConfidence-1,15,90);
 queueStudioMoment(null,'ownedStreamingLaunch',{kicker:'DIRECT TO THE AUDIENCE',title:`${p.name} goes live`,tone:'great',result:`${p.subscribers.toFixed(2)}M SUBSCRIBERS`,summary:`${state.studio.name} has committed ${money(m.launchCost)} to becoming a direct-to-consumer distributor as well as a film studio. The platform can create recurring subscription revenue, but it now needs a reason for audiences to keep paying.`,stats:[['Launch model',m.short],['Launch cost',money(m.launchCost)],['Opening subscribers',`${p.subscribers.toFixed(2)}m`],['Launch library',`${seeded.length} titles`]],sections:[{title:'The trade-off',text:'Putting a film on your own service sacrifices an external streaming cheque. In return, strong exclusives can attract and retain subscribers, and the platform becomes a corporate asset if it reaches sustainable scale.'},{title:'The burden',text:'Technology, customer acquisition and service operations now add a permanent weekly cost. A stale catalogue creates churn; there is no automatic profit just because the studio owns the platform.'}]});
 if(typeof surfacePendingStudioMoment==='function')surfacePendingStudioMoment();save();render();return true;
}
function ownedStreamingFilmBoost(f){const p=ensureOwnedStreamingState(),m=ownedStreamingModel(p.model),strength=afterlifeStrength(f),age=Math.max(0,state.week-(f.completeWeek||state.week)),fresh=Math.max(.35,1-age/104),prestige=m?.id==='prestige'?Math.max(0,(f.review?.critics||60)-70)*.002:0,event=m?.id==='event'?Math.max(0,(f.finalGross||0)-80)*.00055:0;return +clamp((.035+strength*.0022+prestige+event)*fresh*(m?.releaseMult||1),.035,.62).toFixed(3)}
function assignFilmToOwnedPlatform(f,launchSeed=false){
 const p=ensureOwnedStreamingState();if(p.status!=='active'||!f||f.stage!=='complete')return false;const s=ensureStreamingState(f);if(s.activeDeal)return false;if(s.ownedPlatform)return true;
 if(s.offers?.length){s.offers=[];resolveStreamingDeskItem(f,`${p.name} retained the film for the studio's own platform.`)}
 s.ownedPlatform={name:p.name,startWeek:state.week};s.nextOfferWeek=null;if(!p.exclusiveFilmIds.includes(f.id))p.exclusiveFilmIds.push(f.id);p.lastExclusiveWeek=state.week;
 const boost=launchSeed?0:ownedStreamingFilmBoost(f);if(boost){p.subscribers=+clamp(p.subscribers+boost,.05,40).toFixed(3);p.peakSubscribers=Math.max(p.peakSubscribers,p.subscribers)}
 p.history.unshift({week:state.week,type:'title',filmId:f.id,title:f.title,boost,launchSeed});p.history=p.history.slice(0,60);
 if(!launchSeed)addNews(state,`${f.title} will stream exclusively on ${p.name}. The title adds roughly ${boost.toFixed(2)}m subscribers to the platform's current base.`,'Library');
 if(!launchSeed){save();render()}return true;
}
function releaseFilmFromOwnedPlatform(f){const p=ensureOwnedStreamingState(),s=ensureStreamingState(f);if(!s.ownedPlatform)return false;const age=state.week-(s.ownedPlatform.startWeek||state.week);if(age<26)return showToast(`Keep the film on ${p.name} for at least 26 weeks before returning it to the market.`);s.ownedPlatform=null;s.nextOfferWeek=state.week+4;p.exclusiveFilmIds=p.exclusiveFilmIds.filter(id=>id!==f.id);p.history.unshift({week:state.week,type:'rights-return',filmId:f.id,title:f.title});addNews(state,`${state.studio.name} has returned ${f.title}'s streaming rights to the open market after its run on ${p.name}.`,'Library');save();render();return true}
function collectOwnedStreamingWeeklyRevenue(){const p=ensureOwnedStreamingState();if(p.status!=='active')return 0;const revenue=ownedStreamingWeeklyRevenue(),cost=ownedStreamingWeeklyOverhead();p.lastWeeklyRevenue=revenue;p.lastWeeklyCost=cost;p.lastWeeklyNet=+(revenue-cost).toFixed(4);p.lifetimeRevenue=+(p.lifetimeRevenue+revenue).toFixed(3);p.lifetimeOperatingCost=+(p.lifetimeOperatingCost+cost).toFixed(3);p.currentQuarterRevenue=+(p.currentQuarterRevenue+revenue).toFixed(3);p.currentQuarterCost=+(p.currentQuarterCost+cost).toFixed(3);state.cash+=revenue;return revenue}
function ownedStreamingQuarterGrowth(){const p=ensureOwnedStreamingState(),m=ownedStreamingModel(p.model),ids=p.exclusiveFilmIds||[],films=ids.map(filmById).filter(Boolean),fresh=films.filter(f=>state.week-(ensureStreamingState(f).ownedPlatform?.startWeek||0)<=13),recent=films.filter(f=>state.week-(ensureStreamingState(f).ownedPlatform?.startWeek||0)<=26);let pct=.008+Math.min(.035,ids.length*.003)+(ensureStudioGrowth().recognition-70)*.0012;pct+=fresh.reduce((s,f)=>s+clamp((afterlifeStrength(f)-55)/420,0,.09),0);if(m?.id==='prestige')pct+=fresh.reduce((s,f)=>s+Math.max(0,(f.review?.critics||0)-78)*.002,0);if(m?.id==='event')pct+=fresh.reduce((s,f)=>s+Math.max(0,(f.finalGross||0)-120)*.00045,0);if(!recent.length)pct-=m?.churn||.04;if(state.week-(p.lastExclusiveWeek||p.launchWeek||state.week)>=39)pct-=(m?.churn||.04)*.7;if(p.subscribers>12)pct-=.015;return clamp(pct,-.16,.22)}
function processOwnedStreamingQuarter(){const p=ensureOwnedStreamingState();if(p.status!=='active'||state.week%13!==0||state.week===p.lastQuarterWeek)return false;const before=p.subscribers,pct=ownedStreamingQuarterGrowth(),after=+clamp(before*(1+pct),.05,40).toFixed(3),net=+(p.currentQuarterRevenue-p.currentQuarterCost).toFixed(2);p.subscribers=after;p.peakSubscribers=Math.max(p.peakSubscribers,after);p.lastQuarterSubscribers=after;p.lastQuarterWeek=state.week;const q={week:state.week,subscribers:after,change:+((after-before)).toFixed(3),changePct:+(pct*100).toFixed(1),revenue:+p.currentQuarterRevenue.toFixed(2),cost:+p.currentQuarterCost.toFixed(2),net};p.quarterly.unshift(q);p.quarterly=p.quarterly.slice(0,24);p.history.unshift({week:state.week,type:'quarter',...q});p.history=p.history.slice(0,60);p.currentQuarterRevenue=0;p.currentQuarterCost=0;
 if(Math.abs(pct)>=.055||Math.abs(net)>=4){const dir=pct>=0?'grew':'shrunk';pushDeskItem({templateId:'streaming-quarter',repeatKey:`streaming-quarter:${state.week}`,family:'corporate',type:'finance',source:`${p.name} Operations`,urgency:net<-4?'urgent':'normal',requiresAction:false,resolved:true,read:false,expanded:false,headline:`${p.name} ${dir} to ${after.toFixed(2)}m subscribers`,body:`The latest quarter generated ${money(q.revenue)} in subscription receipts against ${money(q.cost)} of platform operating cost, a ${net>=0?'positive':'negative'} contribution of ${money(Math.abs(net))}. Subscriber change was ${pct>=0?'+':''}${q.changePct}%.`});
  if(Math.abs(pct)>=.075||Math.abs(net)>=5)addNews(state,`${p.name} ${dir} ${Math.abs(q.changePct).toFixed(1)}% in the latest quarter to ${after.toFixed(2)}m subscribers, while the service produced ${net>=0?'a positive contribution of':'an operating loss of'} ${money(Math.abs(net))}.`,'Trade Finance');
 }
 return true}
function ownedStreamingInvestorSignal(){const p=ensureOwnedStreamingState(),q=p.quarterly?.[0];if(p.status!=='active'||!q||q.week!==state.week)return 0;return clamp((q.changePct||0)*.08+(q.net||0)*.18,-4,4)}
function ownedStreamingHealthLabel(){const p=ensureOwnedStreamingState(),net=ownedStreamingWeeklyNet();if(p.status!=='active')return 'Not operating';if(net>=.20)return 'Scaling profitably';if(net>=0)return 'Around break-even';if(net>=-.20)return 'Investment phase';return 'Heavy cash burn'}
function windDownOwnedStreamingPlatform(){const p=ensureOwnedStreamingState();if(p.status!=='active')return false;if(state.week-(p.launchWeek||state.week)<52)return showToast('The platform must operate for at least one year before a full wind-down.');const cost=+clamp(5+p.subscribers*.8,5,18).toFixed(1);if(state.cash<cost)return showToast(`A controlled wind-down needs ${money(cost)} for contracts, staff and customer obligations.`);const wasNet=ownedStreamingWeeklyNet();state.cash-=cost;(p.exclusiveFilmIds||[]).map(filmById).filter(Boolean).forEach(f=>{const s=ensureStreamingState(f);s.ownedPlatform=null;s.nextOfferWeek=state.week+4});p.exclusiveFilmIds=[];p.status='wound_down';p.woundDownWeek=state.week;p.history.unshift({week:state.week,type:'wind-down',cost,subscribers:p.subscribers});const oldSubs=p.subscribers;p.subscribers=0;if(ensureCorporateState().status==='public')ensureCorporateState().investorConfidence=clamp(ensureCorporateState().investorConfidence+(wasNet<0?1:-4),15,90);addNews(state,`${state.studio.name} will wind down ${p.name} after reaching ${oldSubs.toFixed(2)}m subscribers. The closure will cost about ${money(cost)} and return its film rights to the open market.`,'Trade Finance');queueStudioMoment(null,'ownedStreamingWindDown',{kicker:'THE PLATFORM GOES DARK',title:`${p.name} will close`,tone:'warn',result:`${money(cost)} WIND-DOWN`,summary:`The studio has ended its direct-to-consumer experiment. The films remain valuable; only the subscription operation is closing.`,stats:[['Final subscribers',`${oldSubs.toFixed(2)}m`],['Closure cost',money(cost)],['Lifetime receipts',money(p.lifetimeRevenue)],['Operating cost',money(p.lifetimeOperatingCost)]],sections:[{title:'Rights return home',text:'Titles that were exclusive to the platform return to the studio’s open catalogue and can receive outside streaming offers again.'},{title:'A corporate scar, not a Game Over',text:'Closing a platform can hurt confidence if it was profitable, or look disciplined if it was burning cash. Either way, the film studio continues.'}]});if(typeof surfacePendingStudioMoment==='function')surfacePendingStudioMoment();save();render();return true}
function pendingOwnedStreamingDeskItem(){return ensureDesk().items.find(x=>!x.resolved&&x.templateId==='streaming-feasibility')||null}
function maybeSurfaceOwnedStreamingOpportunity(){if(state.week%13!==0)return false;const p=ensureOwnedStreamingState(),e=ownedStreamingLaunchEligibility();if(!e.ok||pendingOwnedStreamingDeskItem()||(p.notifiedWeek&&state.week-p.notifiedWeek<52))return false;p.notifiedWeek=state.week;pushDeskItem({templateId:'streaming-feasibility',repeatKey:`streaming-feasibility:${Math.ceil(state.week/52)}`,family:'corporate',type:'finance',source:'Corporate Strategy',urgency:'action',requiresAction:true,expiresWeek:state.week+8,subject:state.studio.name,headline:`${state.studio.name} can now support its own streaming platform`,body:`The catalogue, brand and balance sheet are finally large enough to support a direct-to-consumer service. The Corporate team has prepared three launch models. This is optional: remaining a film studio carries no penalty.`,choices:[['review','Review platform plans'],['later','Shelve it for now']]});return true}
function resolveOwnedStreamingDeskChoice(item,key){if(item?.templateId!=='streaming-feasibility')return null;const p=ensureOwnedStreamingState();if(key==='later'){p.declinedUntil=state.week+52;return 'The studio shelves direct-to-consumer streaming for another year and keeps licensing titles to outside platforms.'}if(key==='review'){state.screen='studio';state.detail=null;state.uiStudioTab='corporate';return 'The Corporate team opens the streaming-platform launch models for review.'}return null}
function ownedStreamingCorporatePanel(){const p=ensureOwnedStreamingState(),e=ownedStreamingLaunchEligibility();if(p.status==='none')return `<div class="section-title"><h2>Direct-to-consumer streaming</h2><span class="small">Major late-career expansion</span></div>${e.ok?`<div class="card attention"><div class="body"><strong>${ownedStreamingPlatformName()} is feasible.</strong> This is not another licensing deal. The studio would become responsible for technology, subscriber acquisition and retention while choosing which films to withhold from outside streamers.</div></div><div class="grid cols3" style="margin-top:10px">${Object.values(OWNED_STREAMING_MODELS).map(m=>`<button class="card" data-launch-streaming-model="${m.id}" ${state.cash<m.launchCost?'disabled':''}><div class="row"><strong>${m.short}</strong><span class="pill">${money(m.launchCost)}</span></div><div class="body" style="margin-top:7px">${m.label}</div><div class="small" style="margin-top:7px">${m.desc}</div><div class="small" style="margin-top:8px">Base operation ${moneyFine(m.fixedOverhead)}/week before subscriber servicing.</div></button>`).join('')}</div>`:`<div class="card"><div class="body">Owning a platform only becomes credible once the film business is already large enough to support it.</div><div style="margin-top:8px">${e.reasons.map(x=>`<div class="small">• ${x}</div>`).join('')}</div></div>`}`;if(p.status==='wound_down')return `<div class="section-title"><h2>Direct-to-consumer streaming</h2></div><div class="card"><strong>${p.name} · closed</strong><div class="body" style="margin-top:7px">The studio exited direct-to-consumer streaming in Week ${p.woundDownWeek}. Film rights have returned to the open catalogue. The closure remains part of the company’s corporate history.</div></div>`;
 const m=ownedStreamingModel(p.model),net=ownedStreamingWeeklyNet(),q=p.quarterly?.[0];return `<div class="section-title"><h2>${p.name}</h2><span class="pill ${net>=0?'good':net<-.2?'bad':'warn'}">${ownedStreamingHealthLabel()}</span></div><div class="grid cols4"><div class="card"><div class="badge">Subscribers</div><div class="kpi">${p.subscribers.toFixed(2)}m</div><div class="small">peak ${p.peakSubscribers.toFixed(2)}m</div></div><div class="card"><div class="badge">Weekly receipts</div><div class="kpi">${moneyFine(ownedStreamingWeeklyRevenue())}</div></div><div class="card"><div class="badge">Weekly operation</div><div class="kpi">${moneyFine(ownedStreamingWeeklyOverhead())}</div></div><div class="card"><div class="badge">Weekly contribution</div><div class="kpi ${net>=0?'goodtext':'badtext'}">${net>=0?'+':''}${moneyFine(net)}</div></div></div><div class="card" style="margin-top:10px"><div class="listrow"><span>Model</span><strong>${m.label}</strong></div><div class="listrow"><span>Exclusive studio titles</span><strong>${p.exclusiveFilmIds.length}</strong></div><div class="listrow"><span>Lifetime subscription receipts</span><strong>${money(p.lifetimeRevenue)}</strong></div><div class="listrow"><span>Recorded platform operating cost</span><strong>${money(p.lifetimeOperatingCost)}</strong></div>${q?`<div class="listrow"><span>Latest quarter</span><strong>${q.changePct>=0?'+':''}${q.changePct}% subs · ${q.net>=0?'+':''}${money(q.net)}</strong></div>`:''}<div class="small" style="margin-top:8px">Strong exclusive films can grow subscribers. If the exclusive pipeline goes quiet, churn accelerates. External streaming cheques remain available for films you do not keep for ${p.name}.</div></div>${state.week-(p.launchWeek||state.week)>=52?`<button id="windDownStreamingPlatform" class="btn ghost block" style="margin-top:10px">Wind down ${p.name}</button>`:''}`}
