// Project Slate UI: develop

function developmentRouteCards(active='market'){
 const routes=[
  {id:'market',title:'Buy from Market',price:'Usually $0.2m–$0.8m',time:'Immediate',control:'Lowest control',desc:'Pick from finished screenplays already circulating. Usually the cheapest and fastest route, but the material and rights package already exist.',action:'Browse market'},
  {id:'commission',title:'Commission',price:'Usually $0.7m–$1.7m',time:'3 weeks',control:'Guided control',desc:'Choose genre, audience, scale and strategic brief, then hire a writer. More control, more time and more development cost.',action:'Commission script'},
  {id:'concept',title:'Create Original',price:'Usually $1.3m–$2.6m',time:'4 weeks',control:'Maximum control',desc:'Define the property yourself: title, premise, audience, scale and creative intent. Most expensive, but you own the IP outright.',action:'Create original'}
 ];
 return `<div class="section-title"><h2>Source your next film</h2><span class="small">Creative control is earned as the studio establishes itself</span></div><div class="grid cols3">${routes.map(r=>{const access=developmentRouteAccess(r.id),locked=!access.unlocked;return `<div class="card ${active===r.id?'goodline':''} ${locked?'route-locked':''}"><div class="row"><strong>${r.title}</strong><span class="pill ${locked?'bad':r.id==='market'?'good':r.id==='commission'?'blue':'warn'}">${locked?'Locked':r.control}</span></div><div class="kpi" style="font-size:17px;margin-top:9px">${r.price}</div><div class="small">${r.time}</div><div class="body" style="margin-top:9px">${locked?access.text:r.desc}</div>${locked?`<div class="milestone-progress" style="margin-top:10px"><span style="width:${access.progress}%"></span></div><div class="small" style="margin-top:5px">Creative reputation ${Math.round(state.reputation.creative)} / ${access.need}</div><button class="btn block" style="margin-top:10px" disabled>${access.label}</button>`:active===r.id?`<button class="btn primary block" style="margin-top:10px" disabled>Current route</button>`:r.id==='market'?`<button class="btn block" data-script-tab="market" style="margin-top:10px">${r.action}</button>`:r.id==='commission'?`<button class="btn block" id="routeCommission" style="margin-top:10px">${r.action}</button>`:`<button class="btn block" id="routeConcept" style="margin-top:10px">${r.action}</button>`}</div>`}).join('')}</div>`;
}
function scriptsScreen(){
 const tab=state.uiScriptTab||'market';
 const market=state.market.map(scriptById).filter(Boolean).sort((a,b)=>{const sa=typeof screenplayMarketSnapshot==='function'?screenplayMarketSnapshot(a):null,sb=typeof screenplayMarketSnapshot==='function'?screenplayMarketSnapshot(b):null;return Number(!!sb?.auction)-Number(!!sa?.auction)||Number(!!sb?.playerBid)-Number(!!sa?.playerBid)||Number(!!b.turnaround)-Number(!!a.turnaround)||(scriptMarketAppeal(b)-scriptMarketAppeal(a))}),owned=state.scripts.filter(s=>s.owner==='player'&&!s.filmStarted),writing=owned.filter(s=>s.status==='writing'),ready=owned.filter(s=>s.status==='owned');
 const commissionAccess=developmentRouteAccess('commission'),conceptAccess=developmentRouteAccess('concept');
 const tabs=`<div class="industrytabs"><button class="btn ${tab==='market'?'primary':''}" data-script-tab="market">Script Market</button><button class="btn ${tab==='owned'?'primary':''}" data-script-tab="owned">Owned ${owned.length?`(${owned.length})`:''}</button><button class="btn" id="newCommission" ${commissionAccess.unlocked?'':'disabled'}>Commission${commissionAccess.unlocked?'':' · 🔒'}</button><button class="btn" id="newConcept" ${conceptAccess.unlocked?'':'disabled'}>Create Original${conceptAccess.unlocked?'':' · 🔒'}</button></div>`;
 let body='';
 if(tab==='owned'){
  body=`<div class="section-title"><h2>Your development library</h2><span class="small">${ready.length} ready · ${writing.length} being written</span></div>
  <div class="grid">${owned.length?owned.map(s=>{ensureScriptEcosystem(s);const w=writerById(s.writerId),cov=s.status==='owned'?scriptCoverage(s):null;return `<div class="card click ${s.status==='writing'?'attention':''}" data-script="${s.id}"><div class="row"><div><strong>${s.title}</strong><div class="small">${s.genre} · ${w?.name||'Writer TBA'}</div></div>${s.status==='writing'?`<span class="pill warn">Draft W${s.dueWeek}</span>`:`<span class="pill ${cov?.readiness==='Packaging-ready'?'good':'blue'}">${cov?.readiness||'Owned'}</span>`}</div><div class="body" style="margin-top:8px">${s.logline}</div><div style="margin-top:8px"><span class="pill blue">${s.franchiseMode?franchiseModeLabel(s.franchiseMode):sourceRouteLabel(s.source)}</span><span class="pill">${scriptRightsText(s)}</span><span class="pill">${money(s.developmentSpend||0)} invested</span></div></div>`}).join(''):`<div class="card body">You do not currently control any unproduced screenplays.</div>`}</div>`;
 }else{
  const activeAuctions=market.filter(s=>typeof screenplayMarketSnapshot==='function'&&screenplayMarketSnapshot(s).auction).length,turnarounds=market.filter(s=>s.turnaround).length,liveBids=market.filter(s=>typeof screenplayMarketSnapshot==='function'&&screenplayMarketSnapshot(s).playerBid).length;
  body=`${developmentRouteCards('market')}<div class="market-strip"><div><span>LIVE MARKET</span><strong>${market.length} scripts</strong></div><div><span>AUCTIONS</span><strong>${activeAuctions}</strong></div><div><span>YOUR BIDS</span><strong>${liveBids}</strong></div><div><span>TURNAROUNDS</span><strong>${turnarounds}</strong></div></div><div class="section-title"><h2>Available finished screenplays</h2><span class="small">Rival interest and bids now move while the calendar advances</span></div>
  <div class="grid">${market.map(s=>{ensureScriptEcosystem(s);const range=naturalRange(s),w=writerById(s.writerId),heat=scriptHeat(s),marketMeta=typeof screenplayMarketCardMeta==='function'?screenplayMarketCardMeta(s):'';return `<div class="card click ${s.turnaround?'turnaround-listing':''}" data-script="${s.id}"><div class="row"><div><strong>${s.title}</strong><div class="small">${s.genre} · ${w?.name||'Unknown writer'}</div></div><div><strong>${money(s.price)}</strong><div class="small">asking</div></div></div><div class="body" style="margin-top:8px">${s.logline}</div><div style="margin-top:8px"><span class="pill">${money(range[0])}–${money(range[1])}</span><span class="pill ${heat.cls}">${heat.label}</span>${scriptFirstLookActive(s)?`<span class="pill good" title="Rival studios cannot bid until Week ${s.firstLookUntil}">Exclusive First Look · rivals locked until W${s.firstLookUntil}</span>`:''}<span class="pill">${scriptRightsText(s)}</span>${marketMeta}</div></div>`}).join('')}</div>${typeof screenplayRecentDealsHTML==='function'?screenplayRecentDealsHTML():''}`;
 }
 return topbar('Development','Scripts, commissions, owned material and future IP')+`<main class="screen">${tabs}${body}</main>${nav()}`;
}
function scriptPassFeedbackHTML(s){
 const used=s.rewrites?.length||0,latest=s.rewrites?.at(-1),r=latest?.result||s.lastRewriteResult;
 const slots=`<div class="pass-slots">${[0,1].map(i=>`<div class="pass-slot ${i<used?'used':''}"><span>${i<used?'✓':'○'}</span><strong>${i<used?`Pass ${i+1} complete`:`Pass ${i+1} available`}</strong></div>`).join('')}</div>`;
 if(!latest||!r)return `<div class="development-pass-status"><div class="row"><strong>Major development passes</strong><span class="pill">${used}/2 used</span></div>${slots}<div class="small" style="margin-top:8px">Each pass consumes one week and permanently changes the working draft. You have two major opportunities before packaging.</div></div>`;
 return `<div class="development-pass-status pass-complete"><div class="row"><div><div class="badge">LATEST DRAFT · PASS ${used} COMPLETE</div><strong class="pass-headline">${r.headline}</strong></div><span class="pill good">${used}/2 used</span></div>
 ${slots}
 <div class="body" style="margin-top:10px">${scriptPassResultText(r)}</div>
 ${r.changes?.length?`<div class="pass-changes">${r.changes.map(x=>`<span class="pill ${x.direction==='down'?'warn':'good'}">${x.label} · ${x.direction==='down'?'trade-off':x.band}</span>`).join('')}</div>`:''}
 ${r.readinessChanged?`<div class="pass-readiness"><span>${r.readinessBefore}</span><b>→</b><strong>${r.readinessAfter}</strong></div>`:''}
 </div>`;
}
function scriptDetail(id){
 const s=ensureScriptEcosystem(scriptById(id)),range=naturalRange(s),w=writerById(s.writerId),heat=scriptHeat(s),cov=s.status==='owned'?scriptCoverage(s):null;
 if(s.status==='writing')return topbar('Script Development',s.genre)+`<main class="screen">${backHead(s.title,s.franchiseMode?franchiseModeLabel(s.franchiseMode):sourceRouteLabel(s.source))}<div class="hero"><div class="row"><span class="pill blue">${s.franchiseMode?franchiseModeLabel(s.franchiseMode):sourceRouteLabel(s.source)}</span><span class="pill">${money(s.developmentSpend||0)} development cost</span></div><div class="quote" style="margin-top:8px">${s.logline}</div><div class="body" style="margin-top:10px">${w?.name||'The writer'} is working from your brief. Draft delivery is expected around <strong>Week ${s.dueWeek}</strong>.</div></div><div class="grid cols3" style="margin-top:12px"><div class="card"><div class="badge">Writer</div><strong>${w?.name||'TBA'}</strong></div><div class="card"><div class="badge">Target scale</div><strong>${s.commissionBrief?.scale||'Mid'}</strong></div><div class="card"><div class="badge">Audience</div><strong>${s.commissionBrief?.audience||'Mainstream Adults'}</strong></div></div>${s.creativeIntent?`<div class="card" style="margin-top:12px"><div class="row"><strong>Studio creative intent</strong><span class="pill good">Carried into film development</span></div><div style="margin-top:8px"><span class="pill">${s.creativeIntent.positioning}</span><span class="pill">${s.creativeIntent.tone}</span><span class="pill">${s.creativeIntent.rating}</span><span class="pill">${s.creativeIntent.emphasis}</span></div></div>`:''}</main>${nav()}`;
 const report=cov?`<div class="section-title"><h2>Coverage</h2><span class="pill ${cov.readiness==='Packaging-ready'?'good':cov.readiness==='Needs development'?'bad':'blue'}">${cov.readiness}</span></div><div class="grid cols2"><div class="card goodline"><strong>What is working</strong>${cov.strengths.map(x=>`<div class="small" style="margin-top:8px">• ${x.text}</div>`).join('')}</div><div class="card ${cov.readiness==='Needs development'?'dangerline':''}"><strong>Development concerns</strong>${cov.concerns.map(x=>`<div class="small" style="margin-top:8px">• ${x.text}</div>`).join('')}</div></div>`:
 `<div class="section-title"><h2>Development assessment</h2></div><div class="card body">${scriptAssessment(s)}</div>`;
 let actions='';
 if(s.status==='market'&&s.available){
  actions=typeof screenplayMarketActionHTML==='function'?screenplayMarketActionHTML(s):`<button id="acquireScript" class="btn primary block" style="margin-top:14px">Acquire rights · ${money(s.price)}</button>`;
 }else if(s.owner==='player'&&s.status==='owned'&&!s.filmStarted){
  const passes=scriptPassOptions(s),usedTypes=(s.rewrites||[]).map(x=>x.type);
  actions=`<div class="section-title"><h2>Development choices</h2><span class="small">${2-s.rewrites.length} major pass${2-s.rewrites.length===1?'':'es'} remaining</span></div>
  ${scriptPassFeedbackHTML(s)}
  <div class="grid cols2" style="margin-top:12px">${passes.map(p=>`<button class="card development-pass-choice ${usedTypes.includes(p.id)?'pass-used-before':''}" data-script-pass="${p.id}" ${s.rewrites.length>=2?'disabled':''}><div class="row"><strong>${p.label}</strong>${usedTypes.includes(p.id)?'<span class="pill">Used before</span>':''}</div><div class="small" style="margin-top:5px">${p.desc}</div><div class="small" style="margin-top:7px"><strong>${money(p.cost)}</strong> · consumes one week</div></button>`).join('')}</div>
  <button id="beginScriptFilm" class="btn primary block" style="margin-top:14px">Move into Film Development</button>`;
 }else actions=`<div class="card body">These rights are no longer available to your studio.</div>`;
 return topbar('Script Detail',s.genre)+`<main class="screen">${backHead(s.title,s.genre)}
 <div class="card"><div class="row"><span class="pill blue">${s.franchiseMode?franchiseModeLabel(s.franchiseMode):sourceRouteLabel(s.source)}</span><span class="pill">${sourceControlLabel(s.source)}</span></div><div class="badge" style="margin-top:10px">Logline</div><div class="quote" style="margin-top:8px">${s.logline}</div>${s.synopsis?`<div class="body" style="margin-top:10px">${s.synopsis}</div>`:''}</div>
 <div class="grid cols3" style="margin-top:12px"><div class="card"><div class="badge">Writer</div><strong>${w?.name||'Unknown'}</strong><div class="small">${w?.tag||''}</div></div><div class="card"><div class="badge">${s.status==='market'?'Asking price':'Development spend'}</div><div class="kpi">${money(s.status==='market'?s.price:s.developmentSpend||0)}</div></div><div class="card"><div class="badge">Natural production</div><div class="kpi">${money(range[0])}–${money(range[1])}</div></div></div>
 <div class="card" style="margin-top:12px"><div class="row"><strong>Rights</strong><span class="pill">${scriptRightsText(s)}</span></div><div class="small" style="margin-top:7px">${s.rights.detail}</div></div>
 ${report}${s.status==='market'?`${typeof screenplayTurnaroundHTML==='function'?screenplayTurnaroundHTML(s):''}<div class="card" style="margin-top:12px"><div class="row"><strong>Market heat</strong><span class="pill ${heat.cls}">${heat.label}</span></div><div class="small" style="margin-top:7px">${heat.text}</div></div>${typeof screenplayBuyerRoomHTML==='function'?screenplayBuyerRoomHTML(s):''}`:''}
 ${actions}</main>${nav()}`;
}
function writerPicker(mode){
 const drafts=ensureWriterDrafts(),d=mode==='concept'?drafts.concept:drafts.commission,q=(drafts.search||'').toLowerCase(),sort=drafts.sort||'fit';
 let writers=state.writers.filter(w=>!q||`${w.name} ${w.tag} ${w.genres.join(' ')}`.toLowerCase().includes(q));
 writers.sort((a,b)=>{
  if(sort==='fit')return writerProjectFit(b,mode)-writerProjectFit(a,mode);
  if(sort==='fee')return writerCommissionCost(a,mode)-writerCommissionCost(b,mode);
  if(sort==='structure')return b.structure-a.structure;
  if(sort==='character')return b.character-a.character;
  if(sort==='dialogue')return b.dialogue-a.dialogue;
  if(sort==='commercial')return b.commercial-a.commercial;
  return a.name.localeCompare(b.name);
 });
 const selected=writerById(d.writerId);
 return topbar('Choose Writer',mode==='concept'?'Original studio property':'Commissioned screenplay')+`<main class="screen pickerpad">${backHead('Writer Shortlist',`${d.genre} · ${mode==='concept'?d.positioning+' original':d.brief+' brief'} · ${developmentRouteInfo(mode,selected,d).cost}`)}
 <div class="filterbar"><input id="writerSearch" class="search" placeholder="Search writers" value="${drafts.search||''}"><select id="writerSort" class="select"><option value="fit" ${sort==='fit'?'selected':''}>Sort: Brief fit</option><option value="fee" ${sort==='fee'?'selected':''}>Sort: Fee</option><option value="structure" ${sort==='structure'?'selected':''}>Sort: Structure</option><option value="character" ${sort==='character'?'selected':''}>Sort: Character</option><option value="dialogue" ${sort==='dialogue'?'selected':''}>Sort: Dialogue</option><option value="commercial" ${sort==='commercial'?'selected':''}>Sort: Commercial</option><option value="name" ${sort==='name'?'selected':''}>Sort: Name</option></select></div>
 <div class="grid">${writers.map(w=>{const fit=writerProjectFit(w,mode),band=fitBand(fit),tags=writerRecommendationTags(w,mode);return `<div class="card"><div class="row"><div class="click" data-writer-profile="${w.id}"><strong>${w.name}</strong><div class="small">${w.tag}</div></div><strong>${money(writerCommissionCost(w,mode))}</strong></div><div style="margin-top:8px"><span class="pill ${band.cls}">${band.label}</span>${tags.map(t=>`<span class="pill blue">${t}</span>`).join('')}</div><div class="grid cols4" style="margin-top:10px"><div><strong>${w.structure}</strong><div class="small">Structure</div></div><div><strong>${w.character}</strong><div class="small">Character</div></div><div><strong>${w.dialogue}</strong><div class="small">Dialogue</div></div><div><strong>${w.commercial}</strong><div class="small">Commercial</div></div></div><div class="small" style="margin-top:9px">${w.genres.join(' · ')} · ${writerRelationshipLabel(w.relationship||0)}</div><button class="btn block ${d.writerId===w.id?'primary':''}" style="margin-top:10px" data-writer-select="${w.id}">${d.writerId===w.id?'Selected':'Select writer'}</button></div>`}).join('')}</div>
 </main><div class="pickerbar"><div class="pickerbar-inner"><div><strong>${selected?selected.name:'No writer selected'}</strong><div class="small">${selected?selected.tag:'Choose a writer for the brief.'}</div></div><button id="writerContinue" class="btn primary" ${selected?'':'disabled'}>Continue</button></div></div>${nav()}`;
}
function writerProfile(id){
 const w=writerById(id);if(!w)return scriptsScreen();
 return topbar('Writer Profile',w.name)+`<main class="screen">${backHead(w.name,w.tag)}
 <div class="grid cols4"><div class="card"><div class="badge">Structure</div><div class="kpi">${w.structure}</div></div><div class="card"><div class="badge">Character</div><div class="kpi">${w.character}</div></div><div class="card"><div class="badge">Dialogue</div><div class="kpi">${w.dialogue}</div></div><div class="card"><div class="badge">Commercial</div><div class="kpi">${w.commercial}</div></div></div>
 <div class="section-title"><h2>Career</h2></div><div class="card"><div class="listrow"><span>Genre evidence</span><strong>${w.genres.join(', ')}</strong></div><div class="listrow"><span>Base fee</span><strong>${money(w.fee)}</strong></div><div class="listrow"><span>Studio relationship</span><strong>${writerRelationshipLabel(w.relationship||0)}</strong></div></div>
 <div class="section-title"><h2>Recent work</h2></div><div class="card">${w.credits?.length?w.credits.slice(0,6).map(c=>`<div class="listrow"><span>${c.title||c}</span><span class="small">${c.week?'W'+c.week:''}</span></div>`).join(''):`<div class="body">No major generated credits yet.</div>`}</div>
 </main>${nav()}`;
}
function conceptScreen(){
 const access=developmentRouteAccess('concept');if(!access.unlocked)return topbar('Create Original','Development access locked')+`<main class="screen">${backHead('Original Development','Earn creative authority first')}${developmentRouteCards('concept')}<div class="card dangerline"><div class="body">${access.text}</div></div></main>${nav()}`;
 const d=ensureWriterDrafts().concept,w=writerById(d.writerId),cost=w?writerCommissionCost(w,'concept'):null;
 return topbar('Create Original','Maximum-control studio-owned IP')+`<main class="screen">${backHead('Create Original Property','Typical draft: 4 weeks')}
 ${developmentRouteCards('concept')}
 <div class="card attention"><div class="row"><strong>Studio development</strong><span class="pill warn">${cost?money(cost):'Usually $1.3m–$2.6m'}</span></div><div class="small" style="margin-top:7px">Most expensive sourcing route. You are funding the property from the idea stage, but retain full screen, sequel and remake rights.</div></div>
 <div class="section-title"><h2>The property</h2><span class="small">Your wording is not scored</span></div>
 <label class="small">Title</label><input id="conceptTitle" class="field" placeholder="Film title" value="${d.title||''}">
 <div class="grid cols2" style="margin-top:12px"><div><label class="small">Genre</label><select id="conceptGenre" class="select">${genres.map(g=>`<option ${d.genre===g?'selected':''}>${g}</option>`).join('')}</select></div><div><label class="small">Target audience</label><select id="conceptAudience" class="select">${audienceNames.map(a=>`<option ${d.audience===a?'selected':''}>${a}</option>`).join('')}</select></div></div>
 <label class="small" style="display:block;margin-top:12px">Logline</label><textarea id="conceptLogline" class="textarea" placeholder="The core dramatic idea.">${d.logline||''}</textarea>
 <label class="small" style="display:block;margin-top:12px">Short synopsis <span class="muted">(optional)</span></label><textarea id="conceptSynopsis" class="textarea" placeholder="More context for the writer and your project record.">${d.synopsis||''}</textarea>
 <div class="section-title"><h2>Creative DNA</h2><span class="small">This becomes the film's starting creative brief</span></div>
 <div class="grid cols2"><div><label class="small">Production scale</label><select id="conceptScale" class="select"><option value="contained" ${d.scale==='contained'?'selected':''}>Contained</option><option value="mid" ${d.scale==='mid'?'selected':''}>Mid-scale</option><option value="large" ${d.scale==='large'?'selected':''}>Large-scale</option></select></div><div><label class="small">Positioning</label><select id="conceptPositioning" class="select"><option value="commercial" ${d.positioning==='commercial'?'selected':''}>Commercial</option><option value="balanced" ${d.positioning==='balanced'?'selected':''}>Balanced</option><option value="prestige" ${d.positioning==='prestige'?'selected':''}>Prestige</option></select></div><div><label class="small">Tone</label><select id="conceptTone" class="select"><option value="grounded" ${d.tone==='grounded'?'selected':''}>Grounded</option><option value="balanced" ${d.tone==='balanced'?'selected':''}>Balanced</option><option value="heightened" ${d.tone==='heightened'?'selected':''}>Heightened</option></select></div><div><label class="small">Audience rating</label><select id="conceptRating" class="select"><option value="broad" ${d.rating==='broad'?'selected':''}>Broad</option><option value="mainstream" ${d.rating==='mainstream'?'selected':''}>Mainstream</option><option value="mature" ${d.rating==='mature'?'selected':''}>Mature</option></select></div></div>
 <label class="small" style="display:block;margin-top:12px">Creative emphasis</label><select id="conceptEmphasis" class="select"><option value="performance" ${d.emphasis==='performance'?'selected':''}>Performance</option><option value="balanced" ${d.emphasis==='balanced'?'selected':''}>Balanced</option><option value="spectacle" ${d.emphasis==='spectacle'?'selected':''}>Spectacle</option></select>
 <div class="section-title"><h2>Screenwriter</h2><span class="small">Writer still determines execution quality</span></div><div class="card ${w?'goodline':''}"><div class="row"><div><strong>${w?w.name:'No writer selected'}</strong><div class="small">${w?`${w.tag} · ${writerRelationshipLabel(w.relationship||0)}`:'Compare writers by fit, fee and strengths.'}</div></div>${w?`<strong>${money(cost)}</strong>`:''}</div><button id="chooseConceptWriter" class="btn block" style="margin-top:10px">${w?'Change writer':'Choose writer'}</button></div>
 <div class="card" style="margin-top:12px"><div class="body"><strong>What you are buying:</strong> control and ownership, not a hidden quality bonus. A weak writer can still turn an expensive original idea into a weak draft.</div></div>
 <button id="commitConcept" class="btn primary block" style="margin-top:14px" ${w&&d.title?.trim()&&d.logline?.trim()?'':'disabled'}>Fund original development${cost?` · ${money(cost)}`:''}</button>
 </main>${nav()}`;
}
function commissionScreen(){
 const access=developmentRouteAccess('commission');if(!access.unlocked)return topbar('Commission Script','Development access locked')+`<main class="screen">${backHead('Commission a Screenplay','Earn creative authority first')}${developmentRouteCards('commission')}<div class="card dangerline"><div class="body">${access.text}</div></div></main>${nav()}`;
 const d=ensureWriterDrafts().commission,w=writerById(d.writerId),cost=w?writerCommissionCost(w,'commission'):null;
 return topbar('Commission Script','Choose the kind of screenplay you want')+`<main class="screen">${backHead('Commission a Screenplay','Typical draft: 3 weeks')}
 ${developmentRouteCards('commission')}
 <div class="card"><div class="row"><strong>Commissioned development</strong><span class="pill blue">${cost?money(cost):'Usually $0.7m–$1.7m'}</span></div><div class="small" style="margin-top:7px">You choose the strategic brief; the writer invents the actual property and execution. Rights are usually cleaner than buying spec material.</div></div>
 <div class="section-title"><h2>The brief</h2></div>
 <div class="grid cols2"><div><label class="small">Genre</label><select id="commissionGenre" class="select">${genres.map(g=>`<option ${d.genre===g?'selected':''}>${g}</option>`).join('')}</select></div><div><label class="small">Target audience</label><select id="commissionAudience" class="select">${audienceNames.map(a=>`<option ${d.audience===a?'selected':''}>${a}</option>`).join('')}</select></div></div>
 <div class="grid cols2" style="margin-top:12px"><div><label class="small">Strategic brief</label><select id="commissionBrief" class="select"><option value="balanced" ${d.brief==='balanced'?'selected':''}>Balanced</option><option value="commercial" ${d.brief==='commercial'?'selected':''}>Commercial</option><option value="prestige" ${d.brief==='prestige'?'selected':''}>Prestige</option><option value="genre" ${d.brief==='genre'?'selected':''}>Genre-first</option></select></div><div><label class="small">Production scale</label><select id="commissionScale" class="select"><option value="contained" ${d.scale==='contained'?'selected':''}>Contained</option><option value="mid" ${d.scale==='mid'?'selected':''}>Mid-scale</option><option value="large" ${d.scale==='large'?'selected':''}>Large-scale</option></select></div></div>
 <div class="section-title"><h2>Screenwriter</h2><span class="small">The brief changes who fits</span></div><div class="card ${w?'goodline':''}"><div class="row"><div><strong>${w?w.name:'No writer selected'}</strong><div class="small">${w?`${w.tag} · ${writerRelationshipLabel(w.relationship||0)}`:'Compare writers by structure, character, dialogue and commercial instincts.'}</div></div>${w?`<strong>${money(cost)}</strong>`:''}</div><button id="chooseCommissionWriter" class="btn block" style="margin-top:10px">${w?'Change writer':'Choose writer'}</button></div>
 <div class="card" style="margin-top:12px"><div class="body">Commissioning sits between the market and a fully original property: more expensive than buying an ordinary spec script, but you control genre, audience, scale and intent before the first page exists.</div></div>
 <button id="commitCommission" class="btn primary block" style="margin-top:14px" ${w?'':'disabled'}>Commission screenplay${cost?` · ${money(cost)}`:''}</button>
 </main>${nav()}`;
}


// Casting and greenlight presentation

function greenlightReviewUI(f){
 const data=greenlightReviewData(f),risk=greenlightRiskLabel(data),c=f.creative||defaultCreative(),producer=producerStrategy(f),effects=effectsApproach(f);
 const roles=data.roleRows;
 return topbar('Greenlight Review',f.title)+`<main class="screen">${backHead('Greenlight Review','Final executive review before production spend')}
 ${filmIdentityHero(f)}
 <div class="greenlight-banner ${risk.cls}"><div><div class="badge">EXECUTIVE DECISION</div><h2>Do we make this movie?</h2><div class="body">This is the last review before ${money(data.commitment)} is committed to production and talent.</div></div><span class="pill ${risk.cls}">${risk.label}</span></div>
 <div class="greenlight-grid">
  <div class="card"><div class="badge">SCREENPLAY</div><div class="kpi small-kpi">${data.coverage.readiness}</div><div class="body">${data.coverage.strengths[0]?.text||'The material has a workable foundation.'}</div></div>
  <div class="card"><div class="badge">PRODUCTION SCALE</div><div class="kpi small-kpi">${money(f.budget)}</div><div class="small">Natural scale ${money(data.natural)} · ${Math.round(data.ratio*100)}% funded</div></div>
  <div class="card"><div class="badge">CASTING EVIDENCE</div><div class="kpi small-kpi">${data.castingEvidence?.label||'Incomplete'}</div><div class="small">${data.director?.name||'No director'} · ${data.castingEvidence?.tested||0}/2 principal roles screen tested</div></div>
  <div class="card"><div class="badge">CASH AFTER COMMITMENT</div><div class="kpi small-kpi">${money(data.cashAfter)}</div><div class="small">Before later post-production and release campaign costs</div></div>
 </div>
 <div class="section-title"><h2>Role package</h2><span class="small">The film is now cast role-by-role</span></div>
 <div class="grid cols2">${roles.map(x=>{const ev=x.evidence;return `<div class="card ${x.role.type==='lead'&&ev?.cls==='good'?'goodline':x.role.type==='lead'&&ev?.cls==='bad'?'dangerline':x.role.type==='lead'&&ev?.cls==='warn'?'attention':''}"><div class="row"><div><div class="badge">${x.role.type==='lead'?'PRINCIPAL':'SUPPORTING'}</div><strong>${x.role.name}</strong></div>${x.talent?portraitHTML(x.talent,'xs'):''}</div><div class="body" style="margin-top:7px">${x.role.desc}</div><div class="small" style="margin-top:8px">${x.talent?`${x.talent.name} · ${ev?.label||'Role fit untested'}`:'Not cast'}</div></div>`}).join('')}</div>
 <div class="section-title"><h2>Production plan</h2></div>
 <div class="card"><div class="listrow"><span>Director</span><strong>${data.director?.name||'—'}</strong></div><div class="listrow"><span>Positioning</span><strong>${c.positioning}</strong></div><div class="listrow"><span>Producer strategy</span><strong>${producer.name}</strong></div><div class="listrow"><span>Effects approach</span><strong>${effects.name}</strong></div><div class="listrow"><span>Production budget</span><strong>${money(f.budget)}</strong></div><div class="listrow"><span>Talent upfront</span><strong>${money(data.talent)}</strong></div><div class="listrow"><span>Production package</span><strong>${money(data.depth)}</strong></div><div class="listrow total"><span>Total commitment now</span><strong>${money(data.commitment)}</strong></div></div>
 ${data.strengths.length?`<div class="section-title"><h2>Reasons to greenlight</h2></div><div class="greenlight-points">${data.strengths.map(x=>`<div class="card goodline"><span>✓</span><div>${x}</div></div>`).join('')}</div>`:''}
 ${data.risks.length?`<div class="section-title"><h2>What could hurt us</h2></div><div class="greenlight-points">${data.risks.map(x=>`<div class="card ${data.unavailable?.some(t=>x.includes(t.name))?'dangerline':'attention'}"><span>!</span><div>${x}</div></div>`).join('')}</div>`:`<div class="card goodline" style="margin-top:14px"><div class="body">The internal review does not identify a major package-level warning. That does not make the film safe — production and audience response remain uncertain.</div></div>`}
 <div class="greenlight-decision"><div><strong>${data.unavailable?.length?'Package availability changed':`Greenlight ${f.title}?`}</strong><div class="small">${data.unavailable?.length?`${data.unavailable.map(t=>t.name).join(', ')} must be resolved before production can begin.`:`This commits ${money(data.commitment)} and moves the film into production.`}</div></div><div class="row"><button id="greenlightBack" class="btn">Return to package</button><button id="confirmGreenlight" class="btn primary" ${data.unavailable?.length?'disabled':''}>${data.unavailable?.length?'GREENLIGHT BLOCKED':'GREENLIGHT FILM'}</button></div></div>
 </main>${nav()}`;
}

function castingPicker(f){
 ensurePackagingState(f);ensureFilmRoles(f);
 const target=castingTargetRole(f),available=pickerList('Actor',f,target.id),chosen=f.cast.map(talentById),slots=Math.max(0,auditionSlotLimit()-f.auditionSlotsUsed);
 const leads=ensureFilmRoles(f).filter(r=>r.type==='lead');
 const parent=f.ipParentId?filmById(f.ipParentId):null,returning=parent?(parent.cast||[]).map(talentById).filter(Boolean):[];
 const mode=f.franchiseMode||scriptById(f.scriptId)?.franchiseMode||'sequel',returningSelected=parent?f.cast.filter(id=>(parent.cast||[]).includes(id)).length:0;
 const continuityNote=!parent?'':mode==='reboot'?`<div class="card goodline" style="margin-bottom:12px"><strong>Continuity reset</strong><div class="small" style="margin-top:6px">This project is being sold as a reboot. New principal casting will not carry the normal recasting penalty, although the film receives less benefit from existing audience familiarity.</div></div>`:mode==='spinoff'?`<div class="card blue" style="margin-bottom:12px"><strong>New branch of the property</strong><div class="small" style="margin-top:6px">A spin-off can build around new principal characters with less continuity pressure than a direct sequel.</div></div>`:`<div class="card ${returningSelected>=2?'goodline':returningSelected===0?'attention':''}" style="margin-bottom:12px"><div class="row"><strong>Audience continuity</strong><span class="pill">${returningSelected}/2 returning leads selected</span></div><div class="small" style="margin-top:6px">${returningSelected>=2?'The principal cast is reunited, preserving the strongest continuity benefit.':returningSelected===1?'Partial continuity: one familiar lead remains, but the audience will notice the recast.':'No returning leads are selected. On a familiar direct continuation, replacing both principals can create resistance unless the new film gives audiences a strong reason to accept it.'}</div></div>`;
 const returningSection=returning.length?`${continuityNote}<div class="section-title"><h2>Returning cast</h2><span class="small">${franchiseModeLabel(mode)} · familiarity ${Math.round(franchiseStatus(parent).familiarity)} · fatigue ${Math.round(franchiseStatus(parent).fatigue)}</span></div><div class="grid cols2">${returning.map(t=>{const held=f.sequelOptions?.includes(t.id),assigned=roleForTalent(f,t.id);return `<div class="card ${assigned?'goodline':''}"><div class="talenthead"><div class="click talentidentity" data-talent="${t.id}">${portraitHTML(t,'sm')}<div><strong>${t.name}</strong><div class="small">${parent.title} · returning principal${assigned?` · ${assigned.name}`:''}</div></div></div><span class="pill ${held?'good':'blue'}">${held?'Sequel option held':'Fresh negotiation'}</span></div><button class="btn block" style="margin-top:10px" data-toggle-cast="${t.id}" ${talentUnavailableForFilm(t,f)?'disabled':''}>Consider for ${target.name}</button></div>`}).join('')}</div>`:'';
 return topbar('Casting',f.title)+`<main class="screen pickerpad">${backHead('Principal Cast',`Cast the role, not just the name · ${f.cast.length}/2 leads attached`)}
 <div class="role-casting-board">${leads.map(role=>{const tid=castingRoleAssignment(f,role.id),t=tid?talentById(tid):null;return `<button class="role-casting-card ${target.id===role.id?'active-role':''} ${t?'filled-role':''}" data-casting-role="${role.id}"><div class="row"><div><div class="badge">${role.id==='lead1'?'LEAD I':'LEAD II'}</div><strong>${role.name}</strong></div>${t?portraitHTML(t,'xs'):'<span class="role-open">OPEN</span>'}</div><div class="small" style="margin-top:7px">${role.desc}</div><div class="role-specs"><span>Screen age ${role.ageMin}–${role.ageMax}</span><span>${role.craft>=.58?'Performance-heavy':role.star>=.30?'Charisma / campaign value':'Balanced demands'}</span></div>${t?`<div class="role-attached">${t.name} · ${castingEvidenceFor(t,f,role.id).label}</div>`:''}</button>`}).join('')}</div>
 <div class="casting-target"><span>Currently casting</span><strong>${target.name}</strong><small>${target.desc}</small></div>
 ${returningSection}
 ${pickerControls('Actor')}
 <div class="card ${slots===0?'attention':''}" style="margin-bottom:12px"><div class="row"><div><strong>Screen-Test Round ${f.auditionRound}</strong><div class="small">A screen test is the only role-specific evidence you get before casting. Market reputation, star power and genre history are known; whether the actor actually unlocks <strong>${target.name}</strong> is not. Talent may decline to test.</div></div><span class="pill ${slots?'blue':'warn'}">${slots}/${auditionSlotLimit()} slots left</span></div>${slots===0?`<button id="extraAuditions" class="btn block" style="margin-top:10px">Open another round · ${money(extraAuditionCost())} + 1 week</button>`:''}</div>
 <div class="grid">${available.map(t=>{
  ensureTalentMarketEconomy(t);const aud=auditionForRole(f,t.id,target.id),decline=talentDeclineForRole(f,t.id,target.id),roleDecline=decline?.mode==='role',auditionDecline=decline?.mode==='audition',tags=dynamicCastingTags(t,f),assigned=roleForTalent(f,t.id),assignedElsewhere=assigned&&assigned.id!==target.id,interest=talentProjectInterest(t,f,target,'select'),signals=actorPublicRoleSignals(t,f,target),draw=actorCommercialDraw(t),evidence=castingEvidenceFor(t,f,target.id);
  return `<div class="card ${decline?'dangerline':assigned?.id===target.id?'goodline':''}"><div class="talenthead"><div class="click talentidentity" data-talent="${t.id}">${portraitHTML(t,'sm')}<div><strong>${t.name}</strong><div class="small">${t.tag} · ${t.careerState}${assigned?` · attached as ${assigned.name}`:''}</div></div></div><div style="text-align:right"><strong>${money(t.fee)}</strong><div class="small">market quote</div></div></div>
  <div style="margin-top:8px"><span class="pill">${actorActingLabel(t.acting)}</span><span class="pill">${actorDrawLabel(draw)}</span><span class="pill">Momentum ${Math.round(t.momentum||60)}</span>${tags.map(x=>`<span class="pill blue">${x}</span>`).join('')}${talentUnavailableForFilm(t,f)?'<span class="pill bad">Unavailable</span>':''}</div>
  ${roleDecline?`<div class="casting-decline"><strong>Passed on ${target.name}</strong><span>${decline.reason}</span></div>`:auditionDecline?`<div class="casting-decline audition-only"><strong>Declined the screen test</strong><span>${decline.reason} You can still make a direct offer for ${target.name}.</span></div>`:''}
  ${aud?`<div class="card ${evidence.cls==='good'?'goodline':evidence.cls==='bad'?'dangerline':evidence.cls==='warn'?'attention':''}" style="margin-top:10px"><div class="row"><strong>Screen test · ${aud.grade}</strong><span class="small">${aud.confidence} confidence</span></div><div class="small" style="margin-top:6px">${aud.note}</div></div>`:`<div class="card" style="margin-top:10px"><div class="badge">ROLE FIT UNKNOWN</div><div class="small" style="margin-top:6px">The market profile is known. Whether ${t.name} actually unlocks ${target.name} is not — run a screen test for role-specific evidence.</div></div>`}
  <div class="hr"></div>${signals.map(x=>`<div class="small" style="margin-top:6px">• ${x}</div>`).join('')}
  <div class="small casting-interest">${agencyWindow(t,f)?`Priority agency conversation through Week ${agencyWindow(t,f).expiresWeek}. `:''}${assignedElsewhere?`${t.name} is already attached as ${assigned.name}.`:aud?`Screen test accepted: representatives are open to ${target.name}; contract terms are still to be agreed.`:auditionDecline?'Representatives would not test, but a direct role offer can still be considered.':f.sequelOptions?.includes(t.id)?'Contractual sequel option held.':interest.score>=72?'Representatives are likely to engage.':interest.score>=50?'Interest looks plausible, not guaranteed.':'There are signs the performer may pass on this role.'}</div>
  <div class="grid cols2" style="margin-top:10px"><button class="btn" data-audition="${t.id}" ${talentUnavailableForFilm(t,f)||aud||decline||assignedElsewhere||slots===0?'disabled':''}>${aud?'Screen tested':auditionDecline?'Test declined':roleDecline?'Passed on role':assignedElsewhere?'Already cast':'Screen test'}</button><button class="btn ${assigned?.id===target.id?'primary':''}" data-toggle-cast="${t.id}" ${talentUnavailableForFilm(t,f)||roleDecline||assignedElsewhere?'disabled':''}>${assigned?.id===target.id?`Selected for ${target.name}`:assignedElsewhere?`Already cast as ${assigned.name}`:`Offer ${target.name}`}</button></div></div>`}).join('')}</div>
 </main><div class="pickerbar"><div class="pickerbar-inner"><div><strong>${chosen.length?chosen.map(x=>x.name).join(' + '):'No actors attached'}</strong><div class="small">${f.cast.length}/2 lead roles filled · currently casting ${target.name}</div></div><button id="pickerContinue" class="btn primary" ${f.cast.length===2?'':'disabled'}>Continue with cast</button></div></div>${nav()}`;
}
function supportingCastingPicker(f){
 ensurePackagingState(f);ensureProductionDepth(f);
 const selected=supportingActors(f),req=supportingCastRequirement(f),supportRoleId=!f.roleAssignments?.support1?'support1':'support2',supportRole=roleById(f,supportRoleId),available=pickerList('Actor',f,supportRole.id).filter(t=>!f.cast.includes(t.id)),selectedIds=new Set(selected.map(t=>t.id));
 return topbar('Supporting Cast',f.title)+`<main class="screen pickerpad">${backHead('Supporting Cast',`${req.label} · ${req.selected}/${req.required||'optional'} required · up to ${req.max} supporting role${req.max===1?'':'s'}`)}
 <div class="cast-scale-hero ${req.complete?'goodline':'attention'}"><div><div class="badge">ENSEMBLE SCALE</div><div class="quote">${req.label}</div><div class="body">${req.required===0?'This production can work with the two leads alone, but a strong third performer can still lift the ensemble.':req.required===1?'At this budget the production needs a credible third performer. The role is no longer decorative: it contributes to performance depth, chemistry, stability and campaign reach.':'This is an event-scale package. Two leads alone would make the film feel undercast, so two supporting performers are required.'}</div>${selected.length<req.max?`<div class="support-role-brief"><strong>Now casting: ${supportRole.name}</strong><span>${supportRole.desc} · screen age ${supportRole.ageMin}–${supportRole.ageMax}</span></div>`:''}</div><div class="cast-scale-count"><strong>${req.selected}/${req.required||'0'}</strong><span>${req.required?'required cast':'required'}</span></div></div>
 ${selected.length?`<div class="section-title"><h2>Selected ensemble</h2><span class="small">Tap a selected performer below to remove them</span></div><div class="selected-support-strip">${selected.map((t,i)=>`<div>${portraitHTML(t,'sm')}<span><strong>Supporting ${i+1}</strong><small>${t.name}</small></span></div>`).join('')}</div>`:''}
 ${pickerControls('Actor')}
 <div class="card"><div class="body"><strong>Why this matters:</strong> supporting performers now contribute directly to the finished ensemble. Strong fit/acting can lift performances and chemistry, reliable performers help production stability, and recognisable supporting names can add publicity value. Larger productions are required to carry a deeper cast.</div></div>
 <div class="grid" style="margin-top:12px">${available.map(t=>{ensureTalentMarketEconomy(t);const assigned=roleForTalent(f,t.id),candidateRole=assigned?.type==='support'?assigned:supportRole,decline=talentDeclineForRole(f,t.id,candidateRole.id),isSelected=selectedIds.has(t.id),signals=actorPublicRoleSignals(t,f,candidateRole),draw=actorCommercialDraw(t);return `<div class="card ${isSelected?'goodline':decline?'dangerline':''}"><div class="talenthead"><div class="click talentidentity" data-talent="${t.id}">${portraitHTML(t,'sm')}<div><strong>${t.name}</strong><div class="small">${t.tag} · ${t.careerState}</div></div></div><div style="text-align:right"><strong>${money(t.fee)}</strong><div class="small">market quote</div></div></div><div style="margin-top:8px"><span class="pill">${actorActingLabel(t.acting)}</span><span class="pill">${actorDrawLabel(draw)}</span><span class="pill">${actorReliabilityLabel(t.reliability)}</span>${talentUnavailableForFilm(t,f)?'<span class="pill bad">Unavailable</span>':''}</div>${decline?`<div class="casting-decline"><strong>Passed on ${candidateRole.name}</strong><span>${decline.reason}</span></div>`:''}<div class="hr"></div>${signals.slice(0,2).map(x=>`<div class="small" style="margin-top:6px">• ${x}</div>`).join('')}<button class="btn block ${isSelected?'primary':''}" style="margin-top:10px" data-select-support="${t.id}" ${((talentUnavailableForFilm(t,f)||selected.length>=req.max||decline)&&!isSelected)?'disabled':''}>${isSelected?`Selected as ${assigned?.name||'support'} · tap to remove`:decline?'Passed on role':selected.length>=req.max?'Supporting package full':`Offer ${supportRole.name}`}</button></div>`}).join('')}</div>
 </main><div class="pickerbar supporting-pickerbar"><div class="pickerbar-inner"><div class="pickerbar-summary"><strong>${selected.length?selected.map(t=>t.name).join(' · '):'No supporting performers selected'}</strong><div class="small">${req.complete?req.required?`${req.label} requirement complete.`:'Optional role — greenlight does not require one.':`${req.required-req.selected} more supporting performer${req.required-req.selected===1?'':'s'} required at the current budget.`}</div></div><div class="pickerbar-actions"><button id="clearSupportingCast" class="btn">${selected.length?'Clear support':'Skip'}</button><button id="supportingContinue" class="btn primary">Return to package</button></div></div></div>${nav()}`;
}
