// Project Slate UI: release

function campaignTimelineIcon(x){return x.type==='trailer'?'▶':x.type==='festivalDecision'?'◆':x.type==='festivalScreening'?'★':x.type==='publicity'?'✦':x.type==='gala'?'✺':'•'}
function campaignResultForMilestone(f,x){const m=ensureMarketingState(f);if(!x.resolved)return 'Planned';if(x.type==='trailer')return momentResultLabel(m.trailerResult?.result);if(x.type==='festivalDecision')return m.festival?.accepted?'Selected':'Not selected';if(x.type==='festivalScreening')return momentResultLabel(m.festival?.result);if(x.type==='publicity')return momentResultLabel(m.publicityResult?.result);if(x.type==='gala')return momentResultLabel(m.premiere?.result);return 'Completed'}
function scheduledUI(f){
 ensureFilmCalendar(f);const lead=marketingLeadInfo(f),m=ensureMarketingState(f),status=marketingPublicStatus(f),pending=m.pending,releaseDay=f.releaseDay||releaseDayForWeek(f.releaseWeek),tracking=preReleaseTracking(f),intel=releaseWindowIntel(f,f.releaseWeek),movable=canMoveReleaseDate(f);
 const moveWeeks=movable?validReleaseWeeks(f).filter(w=>w!==f.releaseWeek&&Math.abs(w-f.releaseWeek)<=3).map(w=>({week:w,intel:releaseWindowIntel(f,w)})).sort((a,b)=>(a.intel.pressure-a.intel.pressure)||(b.intel.season-a.intel.season)).slice(0,4):[];
 const timeline=(m.milestones||[]).map(x=>`<div class="campaignstep ${x.resolved?'done':''}"><div class="campaignicon">${campaignTimelineIcon(x)}</div><div class="campaigncopy"><strong>${marketingMilestoneLabel(x.type)}</strong><div class="small">${campaignResultForMilestone(f,x)}</div></div><div class="campaignweek">${x.day?calendarShortDate(x.day):'W'+x.week}</div></div>`).join('');
 return `<div class="campaignhero"><div><div class="badge">RELEASE CAMPAIGN</div><div class="quote">${f.title}</div><div class="small">Opens ${calendarDateLabel(releaseDay)} · ${lead.tier} · ${money(f.marketing)} paid media · ${distributionLabel(f)}</div></div><div class="campaigncount"><strong>${Math.max(0,calendarDaysUntil(releaseDay))}</strong><span>days to release</span></div></div>
 <div class="grid cols3" style="margin-top:12px"><div class="card"><div class="badge">Campaign reach</div><div class="kpi" style="font-size:18px">${status.heat}</div><div class="small">Internal reach signal ${m.buzz>=0?'+':''}${m.buzz}</div></div><div class="card"><div class="badge">Campaign tone</div><div class="kpi" style="font-size:18px">${status.sentiment}</div><div class="small">${m.sentiment>=0?'+':''}${m.sentiment}</div></div><div class="card"><div class="badge">Expectation pressure</div><div class="kpi" style="font-size:18px">${status.pressure}</div><div class="small">Lift ${m.expectations}</div></div></div>
 <div class="card" style="margin-top:10px"><div class="small"><strong>Campaign vs Pulse:</strong> these numbers describe what the studio is putting into the market — reach, tone and expectation. <strong>Pulse</strong> on the Studio Desk tracks how audiences actually receive it: conversation, sentiment, fandom and controversy.</div></div>
 <div class="section-title"><h2>Industry tracking</h2><span class="pill ${intel.cls}">${tracking.phase}</span></div>
 <div class="tracking-card"><div><div class="badge">PROJECTED DOMESTIC OPENING</div><div class="tracking-range">${money(tracking.low)}–${money(tracking.high)}</div><div class="small">Midpoint ${money(tracking.center)} · tracking is an estimate, not a promise</div></div><div class="tracking-window"><strong>${intel.label}</strong><span>${intel.text}</span></div></div>
 ${m.trackingHistory?.length>1?`<div class="tracking-history">${m.trackingHistory.slice(0,5).map((x,i)=>`<div><span>${x.day?calendarShortDate(x.day):'W'+x.week}</span><strong>${money(x.low)}–${money(x.high)}</strong><small>${x.reason||x.phase}</small></div>`).join('')}</div>`:''}
 ${pending?`<div class="section-title"><h2>Campaign decision waiting</h2></div><div class="card attention"><div class="quote">${pending.title}</div><div class="body" style="margin-top:8px">${pending.text}</div><div class="small" style="margin-top:8px">If you dismissed the event moment, the decision remains available here.</div><div class="grid cols3" style="margin-top:12px">${pending.type==='viralTrailer'?`<button class="btn" data-marketing-choice="amplify">Amplify · $0.35m</button><button class="btn" data-marketing-choice="protect">Keep positioning</button>`:pending.type==='softTrailer'?`<button class="btn" data-marketing-choice="recut">Recut trailer · $0.45m</button><button class="btn" data-marketing-choice="double">Double down · $0.30m</button><button class="btn" data-marketing-choice="accept">Accept it</button>`:`<button class="btn" data-marketing-choice="reviews">Lead with reviews · $0.25m</button><button class="btn" data-marketing-choice="protect">Keep positioning</button>`}</div></div>`:''}
 <div class="section-title"><h2>Distribution plan</h2></div><div class="card"><div class="row"><div><strong>${distributionLabel(f)}</strong><div class="small">${f.distributorName||state.studio.name}</div></div><span class="pill">${Math.round((f.distributionDeal?.domShare??distributionPlan(f).domShare)*100)}% domestic share</span></div><div class="body" style="margin-top:7px">${distributionTradeoff(f)}</div></div>
 <div class="section-title"><h2>Campaign timeline</h2><span class="small">The campaign now runs on actual dates</span></div><div class="campaignline">${timeline||'<div class="body">No public milestones remain before release.</div>'}<div class="campaignstep"><div class="campaignicon">▥</div><div class="campaigncopy"><strong>Theatrical release</strong><div class="small">Opening weekend begins</div></div><div class="campaignweek">${calendarShortDate(releaseDay)}</div></div></div>
 ${m.publicMoments?.length?`<div class="section-title"><h2>Campaign history</h2><span class="small">What actually happened</span></div><div class="grid cols2">${m.publicMoments.slice(0,6).map(x=>`<div class="card"><div class="row"><strong>${x.title}</strong><span class="pill">${x.day&&typeof calendarShortDate==='function'?calendarShortDate(x.day):'W'+x.week}</span></div><div class="small" style="margin-top:6px">${momentResultLabel(x.result)}</div></div>`).join('')}</div>`:''}
 <div class="section-title"><h2>Calendar strategy</h2><span class="small">${movable?'The date is still movable':'Campaign commitments have effectively locked the date'}</span></div><div class="card ${intel.cls==='bad'?'dangerline':intel.cls==='warn'?'attention':''}"><div class="row"><div><strong>${intel.label}</strong><div class="small">${releaseWeekDescription(f.releaseWeek,f.genre)}</div></div><span class="pill ${intel.cls}">${intel.direct.length} direct rival${intel.direct.length===1?'':'s'}</span></div><div class="body" style="margin-top:8px">${intel.text} The film opens on <strong>${calendarDateLabel(releaseDay)}</strong>; the domestic chart settles on <strong>${calendarDateLabel(sundayForWeek(f.releaseWeek))}</strong>.</div>${movable&&moveWeeks.length?`<div class="section-title compact"><h3>Nearby alternatives</h3><span class="small">Moving now costs ${money(releaseMoveCost(f))}${m.publicMoments?.length?' because the public campaign has begun':''}</span></div><div class="grid cols2">${moveWeeks.map(x=>`<button class="btn release-move-option" data-move-release-week="${x.week}"><span>Week ${x.week}</span><small>${x.intel.label} · ${x.intel.rivals.length} rival release${x.intel.rivals.length===1?'':'s'}</small></button>`).join('')}</div>`:''}</div>`;
}
function cinemaComparisonSeries(f){
 const ownWeeks=f.weeklyResults.map(w=>w.worldWeek??(f.releaseWeek+w.week-1));
 if(!ownWeeks.length)return [];
 const start=Math.min(...ownWeeks),end=Math.max(...ownWeeks);
 const competitors=state.films.filter(x=>x.id!==f.id&&x.weeklyResults&&x.weeklyResults.some(w=>{const ww=w.worldWeek??((x.releaseWeek||start)+w.week-1);return ww>=start&&ww<=end}))
  .map(x=>({film:x,overlap:x.weeklyResults.filter(w=>{const ww=w.worldWeek??((x.releaseWeek||start)+w.week-1);return ww>=start&&ww<=end}).reduce((a,w)=>a+w.dom,0)}))
  .sort((a,b)=>b.overlap-a.overlap).slice(0,3).map(x=>x.film);
 return [f,...competitors];
}
function cinemaComparisonGraph(f){
 const series=cinemaComparisonSeries(f);if(!series.length)return '';
 let weeks=[];series.forEach(x=>x.weeklyResults.forEach(w=>weeks.push(w.worldWeek??((x.releaseWeek||state.week)+w.week-1))));
 weeks=[...new Set(weeks)].sort((a,b)=>a-b);if(!weeks.length)return '';
 const minW=weeks[0],maxW=weeks.at(-1),W=760,H=260,L=48,R=16,T=18,B=42,plotW=W-L-R,plotH=H-T-B;
 const rows=series.flatMap(x=>x.weeklyResults.map(w=>({week:w.worldWeek??((x.releaseWeek||minW)+w.week-1),dom:w.dom}))).filter(x=>x.week>=minW&&x.week<=maxW);
 const maxY=Math.max(5,...rows.map(x=>x.dom))*1.1;
 const xPos=w=>L+(maxW===minW?plotW/2:(w-minW)/(maxW-minW)*plotW),yPos=v=>T+plotH-(v/maxY)*plotH;
 const colors=['#8e98ff','#77d59b','#efc36e','#ef8484'];
 let svg=`<svg class="chartsvg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Domestic weekly box office comparison">`;
 for(let i=0;i<=4;i++){const v=maxY*(i/4),y=yPos(v);svg+=`<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#333a47" stroke-width="1"/><text x="${L-7}" y="${y+4}" text-anchor="end" fill="#9da7b5" font-size="10">${money(v)}</text>`}
 weeks.forEach(w=>{const x=xPos(w);svg+=`<text x="${x}" y="${H-16}" text-anchor="middle" fill="#9da7b5" font-size="10">W${w}</text>`});
 series.forEach((film,i)=>{
  const pts=film.weeklyResults.map(w=>({week:w.worldWeek??((film.releaseWeek||minW)+w.week-1),dom:w.dom})).filter(x=>x.week>=minW&&x.week<=maxW).sort((a,b)=>a.week-b.week);
  if(!pts.length)return;const points=pts.map(p=>`${xPos(p.week)},${yPos(p.dom)}`).join(' ');
  svg+=`<polyline points="${points}" fill="none" stroke="${colors[i]}" stroke-width="${i===0?4:2.5}" stroke-linecap="round" stroke-linejoin="round"/>`;
  pts.forEach(p=>svg+=`<circle cx="${xPos(p.week)}" cy="${yPos(p.dom)}" r="${i===0?4:3}" fill="${colors[i]}"/>`);
 });
 svg+='</svg>';
 const legend=series.map((x,i)=>`<span class="legenditem"><span class="legenddot" style="background:${colors[i]}"></span>${x.title}${i===0?' · your film':''}</span>`).join('');
 return `<div class="card chartbox">${svg}<div class="chartlegend">${legend}</div><div class="small" style="margin-top:8px">Domestic weekly gross by calendar week. The comparison follows the strongest films that overlapped your run.</div></div>`;
}
function cinemaUI(f){
 const row=f.weeklyResults.at(-1),settled=!!row?.settledRank,rank=settled?row.settledRank:null,cumSettled=f.weeklyResults.filter(w=>w.settledRank).reduce((a,w)=>a+w.dom+w.intl,0),cum=f.weeklyResults.reduce((a,w)=>a+w.dom+w.intl,0),stats=boxRunStats(f),pace=theatricalPace(f),milestones=settled?boxOfficeMilestones(f):[],be=breakEvenWorldwideEstimate(f);
 const prior=(f.weeklyResults||[]).filter(w=>w!==row&&w.settledRank).at(-1),move=settled&&prior?prior.settledRank-rank:0,dropText=row.drop===null?'Opening week':row.drop<0?`${Math.round(Math.abs(row.drop)*100)}% growth`:`${Math.round(row.drop*100)}% drop`;
 const rankDisplay=settled?`#${rank} ${boxMovementHTML(move)}`:'Weekend in progress',trackStory=settled&&row.week===1?trackingVsActual(f,row.dom):null;
 return `<div class="boxhero ${pace.cls}"><div><div class="badge">Theatrical Week ${f.cinemaWeek}</div><div class="boxrank">${rankDisplay}</div><div class="quote">${f.title}</div><div class="small">${settled?pace.label:'Domestic ranking settles Sunday'} · ${dropText} · ${distributionLabel(f)}</div></div><div class="boxmoney"><div class="badge">${settled?'Worldwide this weekend':'Opening tracking'}</div><div class="kpi">${settled?money(row.dom+row.intl):weekendTrackingLabel(row)}</div><div class="small">${settled?'Cumulative '+money(cum):'Final weekend gross settles Sunday'}</div></div></div>
 <div class="grid cols4" style="margin-top:12px"><div class="card"><div class="badge">Domestic rank</div><div class="kpi">${settled?'#'+rank:'Pending'}</div><div class="small">Peak ${stats.best?'#'+stats.best:'—'}</div></div><div class="card"><div class="badge">Domestic this week</div><div class="kpi">${settled?money(row.dom):'Counting…'}</div><div class="small">${settled?dropText:'Weekend in progress'}</div></div><div class="card"><div class="badge">Worldwide run</div><div class="kpi">${money(settled?cum:cumSettled)}</div><div class="small">Recovery marker ~${money(be)}</div></div><div class="card"><div class="badge">Weeks at #1</div><div class="kpi">${stats.weeksAtOne}</div><div class="small">Settled weekends only</div></div></div>
 ${milestones.length?`<div class="boxbadges">${milestones.map(x=>`<span class="pill ${x.includes('bomb')?'bad':'good'}">${x}</span>`).join('')}</div>`:''}
 ${trackStory?`<div class="tracking-actual ${trackStory.cls}"><div class="badge">TRACKING VS REALITY</div><strong>${trackStory.label}</strong><span>${trackStory.text}</span></div>`:''}
 <div class="section-title"><h2>Weekend story</h2><span class="small">${settled?pace.text:`The full field settles on ${calendarDateLabel(sundayForWeek(state.week))}. Rankings remain provisional until then.`}</span></div><div class="card ${settled&&pace.cls==='good'?'goodline':settled&&pace.cls==='bad'?'dangerline':''}"><div class="body">${settled?weeklyCinemaText(f,row,{rank}):`${f.title} is in cinemas and the weekend is still being counted. Opening and hold grosses are visible, but no chart position is recorded until every competing film has been processed on Sunday.`}</div></div>
   ${theatricalInterventionPanel(f)}\n  ${filmOutcomeFactorsHTML(f)}\n  <div class="section-title"><h2>The box-office race</h2><span class="small">Your run against overlapping releases</span></div>${cinemaComparisonGraph(f)}
 <div class="section-title"><h2>Press & audience</h2></div><div class="card click" id="reviewCard"><div class="row"><div><div class="badge">${f.review.publication}</div><div class="quote" style="margin-top:8px">“${f.review.quote}”</div></div><div class="reviewscore">${f.review.stars.toFixed(1)}★<span>${f.review.critics}%</span></div></div><div class="small" style="margin-top:8px">Audience ${f.review.audience}% · Tap for the full review and segment response</div></div>
 <div class="section-title"><h2>Run history</h2></div><div class="card">${f.weeklyResults.map(w=>`<div class="listrow"><div><strong>Week ${w.week} · ${w.settledRank?'#'+w.settledRank:'Pending'}</strong><div class="small">${w.drop===null?'Opening':w.drop<0?`${Math.round(Math.abs(w.drop)*100)}% domestic growth`:`${Math.round(w.drop*100)}% domestic drop`} · ${w.worldWeek?calendarShortDate(sundayForWeek(w.worldWeek)):''}</div></div><strong>${w.settledRank?money(w.dom+w.intl)+' WW':'Counting…'}</strong></div>`).join('')}</div>`;
}
function weeklyCinemaText(f,row,me){
 const rank=me?.rank||row?.settledRank||'?';
 if(f.cinemaWeek===1){
  if(f.releaseProfile?.type==='bomb')return `${f.title} has opened at #${rank}, but the gross is a genuine commercial shock. Awareness converted poorly and the film now needs extraordinary word of mouth just to stabilise the run.`;
  if(f.releaseProfile?.type==='breakout')return `${f.title} has blown past tracking and opened at #${rank}. The question has immediately changed from “will it work?” to “how large can the run become?”`;
  return `${f.title} opened at #${rank} domestically. ${f.review.audience>=82?'Audience response is strong enough to create real upside if the second weekend holds.':f.review.audience<58?'Weak audience response leaves the film exposed to a severe second-weekend fall.':'The opening is solid; the next hold will decide whether this becomes a run or simply a weekend.'}`;
 }
 if(row.drop<0)return `${f.title} actually grew ${Math.round(Math.abs(row.drop)*100)}% domestically in Week ${f.cinemaWeek}. That is rare: word of mouth is expanding demand rather than merely slowing the normal decline, leaving the film at #${rank}.`;
 if(row.drop<.20)return `${f.title} is showing exceptional legs, down only ${Math.round(row.drop*100)}% and sitting at #${rank}. A hold this strong can keep a film near the top even as newer releases arrive.`;
 if(row.drop>.68)return `${f.title} collapsed ${Math.round(row.drop*100)}% domestically this week and falls to #${rank}. Opening-week demand has been exhausted much faster than the studio wanted.`;
 return `${f.title} declined ${Math.round(row.drop*100)}% domestically in Week ${f.cinemaWeek}, leaving it at #${rank}. The run is now being defined by whether that pace improves or accelerates.`;
}
function reviewScreen(f){
 const roundup=f.pressReviews||[],m=ensureMarketingState(f);
 return topbar('Press Review',f.review.publication)+`<main class="screen">${backHead(f.title,`${f.review.stars.toFixed(1)} / 5 ★ · ${f.review.critics}% critics · ${f.review.audience}% audience`)}
 <div class="hero"><div class="badge">${f.review.stars.toFixed(1)} / 5 ★</div><h2 style="margin:10px 0 6px">${f.review.headline||"The Daily Screen review"}</h2>${f.review.critic?`<div class="small" style="margin-bottom:9px">By <strong>${f.review.critic.name}</strong> · ${f.review.critic.title}</div>`:""}<div class="quote">“${f.review.quote}”</div></div>
 <div class="section-title"><h2>Main review</h2></div><div class="card body">${f.review.paragraphs.map(p=>`<p>${p}</p>`).join('')}</div>
 ${roundup.length?`<div class="section-title"><h2>Critical roundup</h2><span class="small">Capsule verdicts</span></div><div class="grid">${roundup.map(r=>`<div class="card"><div class="row">${pressLogoHTML(r.publication,'xs',true)}<span class="pill">${r.stars.toFixed(1)} / 5 ★</span></div>${r.critic?`<div class="small" style="margin-top:7px">${r.critic} · ${r.voice||"Critic"}</div>`:""}<strong style="display:block;margin-top:9px">${r.headline||r.quote||"Review filed"}</strong></div>`).join('')}</div>`:''}
 ${f.audienceSegments?`<div class="section-title"><h2>Audience segments</h2><span class="small">Post-release response</span></div><div class="grid">${Object.entries(f.audienceSegments).sort((a,b)=>b[1]-a[1]).map(([name,score])=>`<div class="card ${score>=80?'goodline':score<50?'dangerline':''}"><div class="row"><strong>${name}</strong><strong>${Math.round(score)}%</strong></div><div class="small" style="margin-top:5px">${score>=82?'Enthusiastic':score>=70?'Strong':score>=58?'Mixed-positive':score>=48?'Mixed':'Weak'}</div></div>`).join('')}</div>`:''}
 <div class="section-title"><h2>Campaign vs reality</h2></div><div class="card"><div class="listrow"><span>Trailer promise</span><strong>${m.trailer||'concept'}-first</strong></div><div class="listrow"><span>Pre-release heat</span><strong>${marketingPublicStatus(f).heat}</strong></div><div class="listrow"><span>Expectation pressure</span><strong>${marketingPublicStatus(f).pressure}</strong></div>${f.soundtrack?.committed?`<div class="listrow"><span>Music</span><strong>${soundtrackSummary(f)}</strong></div>`:''}${m.advancePress?`<div class="listrow"><span>Advance notices</span><strong>${m.advancePress}</strong></div>`:''}</div>
 ${filmOutcomeFactorsHTML(f)}\n  <div class="section-title"><h2>What the review was responding to</h2></div><div class="card body"><strong>${f.review.sourceContext.title}</strong> · ${f.review.sourceContext.genre}<br><span class="small">${f.review.sourceContext.logline}</span><div class="hr"></div><span class="small"><strong>Finished-film identity:</strong> ${filmIdentityLine(f)}</span></div>
 <div class="grid cols2" style="margin-top:12px"><div class="card"><div class="badge">Critics</div><div class="kpi">${f.review.critics}%</div></div><div class="card"><div class="badge">Audience</div><div class="kpi">${f.review.audience}%</div></div></div>
 </main>${nav()}`;
}
function filmLegacyBadgeClass(l){return l.outcomeClass==='bad'?'bad':l.outcomeClass==='warn'?'warn':l.outcomeClass==='good'?'good':'blue'}
function filmWrapProgress(step){
 const labels=['Curtain','Verdict','Story','People','The Lot'];
 return `<div class="wrap-stagebar"><div class="wrap-stagecount">${String(step+1).padStart(2,'0')} / 05</div><div class="wrap-stagedots">${labels.map((x,i)=>`<span class="${i===step?'active':i<step?'done':''}" title="${x}"></span>`).join('')}</div><div class="wrap-stagelabel">${labels[step]}</div></div>`;
}
function filmWrapMomentScreen(){
 const f=filmById(state.activeFilmWrapId);if(!f)return studioScreen();const l=ensureLegacyState(f);if(!l.built)buildFilmLegacy(f,{});
 const step=Math.max(0,Math.min(4,Number(state.uiFilmWrapStep)||0)),tone=filmWrapTone(f,l),runWeeks=filmWrapRunWeeks(f),story=filmWrapStoryMoments(f),people=filmWrapTalentStories(f,l),trade=filmWrapTradeVerdict(f,l),signals=filmWrapLegacySignals(f,l),a=ensureAfterlifeState(f);
 const date=f.completeDay&&typeof calendarDateLabel==='function'?calendarDateLabel(f.completeDay):'Week '+f.completeWeek;
 const navButtons=(nextLabel)=>`<div class="wrap-actions">${step>0?'<button id="filmWrapBack" class="wrap-text-button">← Back</button>':'<span></span>'}<div class="wrap-action-cluster">${step<4?'<button id="filmWrapSkip" class="wrap-text-button">Skip to verdict</button>':''}<button id="filmWrapNext" class="btn primary wrap-next-button">${nextLabel}</button></div></div>`;
 let chapter='';
 if(step===0){
  chapter=`<section class="wrap-opening wrap-enter"><div class="wrap-opening-poster">${filmKeyArtHTML(f,'hero')}<div class="wrap-poster-shadow"></div></div><div class="wrap-opening-copy"><div class="wrap-kicker">THEATRICAL RUN COMPLETE · ${date}</div>${studioLogoHTML(f.studio||state.studio.name,brandForStudioName(f.studio||state.studio.name,f.owner),'xs',true)}<div class="wrap-endmark">THAT’S A WRAP</div><h1>${f.title}</h1><div class="wrap-opening-meta"><span>${f.genre}</span><span>${runWeeks} theatrical week${runWeeks===1?'':'s'}</span><span>${distributionLabel(f)}</span></div><div class="wrap-opening-verdict">${l.outcome}</div><p>${tone.label}. The final number is in.</p></div></section>${navButtons('See how it ended →')}`;
 }else if(step===1){
  chapter=`<section class="wrap-chapter wrap-enter"><div class="wrap-chapter-kicker">THE FINAL VERDICT</div><h1>${filmWrapVerdictHeadline(f,l)}</h1><div class="wrap-scoreboard"><div class="wrap-score-main"><span>WORLDWIDE</span><strong>${money(f.finalGross)}</strong><small>${money(l.domestic)} domestic · ${money(l.international)} international</small></div><div class="wrap-score-main ${l.profit>=0?'positive':'negative'}"><span>STUDIO RESULT</span><strong>${l.profit>=0?'+':''}${money(l.profit)}</strong><small>${Math.round(l.roi*100)}% film ROI · ${money(f.investment)} invested</small></div></div><p class="wrap-verdict-copy">${filmWrapVerdictCopy(f,l)}</p><div class="wrap-reception-strip"><div><span>Critics</span><strong>${f.review?.critics||0}%</strong></div><div><span>Audience</span><strong>${f.review?.audience||0}%</strong></div><div><span>Peak chart</span><strong>${l.peakRank?'#'+l.peakRank:'—'}</strong></div><div><span>Weeks #1</span><strong>${l.weeksAtOne}</strong></div></div>${l.tags.length?`<div class="wrap-tags cinematic">${l.tags.slice(0,5).map(t=>`<span>${t}</span>`).join('')}</div>`:''}</section>${navButtons('Tell me the story →')}`;
 }else if(step===2){
  chapter=`<section class="wrap-chapter wrap-enter"><div class="wrap-chapter-kicker">THE STORY OF THE FILM</div><h1>Three moments that made ${f.title} what it became.</h1><p class="wrap-verdict-copy">${filmIdentityLine(f)}</p><div class="wrap-timeline">${story.map((m,i)=>`<div class="wrap-timeline-item ${m.tone||'neutral'}"><div class="wrap-timeline-num">0${i+1}</div><div class="wrap-timeline-copy"><div class="wrap-timeline-meta"><span>${m.phase}</span><small>${m.label}</small></div><p>${m.text}</p></div></div>`).join('')||'<div class="wrap-empty-story">The film reached the screen without one dominant production or campaign moment. The run itself became the story.</div>'}</div>${l.callback?`<div class="wrap-memory-strip"><span>THE STUDIO REMEMBERS</span><p>${l.callback.text}</p></div>`:''}</section>${navButtons('Who leaves changed? →')}`;
 }else if(step===3){
  chapter=`<section class="wrap-chapter wrap-enter"><div class="wrap-chapter-kicker">THE PEOPLE WHO CAME OUT DIFFERENT</div><h1>A film ends. Careers keep moving.</h1><div class="wrap-people-grid">${people.map(x=>`<div class="wrap-person"><div class="wrap-person-head">${portraitHTML(x.t,'md')}<div><span>${x.role}</span><strong>${x.name}</strong><small>${relationshipLabel(x.t.relationship||0)} with ${state.studio.name}</small></div></div><p>${x.text}</p><div class="wrap-momentum"><span>Momentum</span><strong>${x.before} <b>→</b> ${x.after}</strong><em class="${x.delta>0?'up':x.delta<0?'down':''}">${x.delta>0?'+':''}${x.delta}</em></div></div>`).join('')||'<div class="wrap-empty-story">No single career moved dramatically. This one belongs more to the studio than to an individual performer.</div>'}</div></section>${navButtons('Hear from The Lot →')}`;
 }else{
  chapter=`<section class="wrap-chapter wrap-final wrap-enter"><div class="wrap-chapter-kicker">THE LOT’S VERDICT</div><div class="wrap-trade-quote"><div class="wrap-quote-mark">“</div><blockquote>${trade.quote}</blockquote><div class="wrap-trade-byline">${pressLogoHTML(trade.journalist.publication,'sm',true)}<div><strong>${trade.journalist.name}</strong><span>${trade.journalist.tone} · ${trade.journalist.beat}</span></div></div></div><div class="wrap-leaves-title">WHAT IT LEAVES BEHIND</div><div class="wrap-leaves-grid">${signals.map(x=>`<div><span>${x.label}</span><strong>${x.value}</strong><small>${x.detail}</small></div>`).join('')}</div><div class="wrap-last-line"><span>THE FILM IS OVER. THE CONSEQUENCES AREN’T.</span><p>${a.cultStatus?'The catalogue is already showing signs of a longer cult life.':'From here, the film moves into the archive, awards conversation and long-tail catalogue economy.'}</p></div></section><div class="wrap-actions wrap-final-actions"><button id="filmWrapBack" class="wrap-text-button">← Back</button><button id="closeFilmWrap" class="btn primary wrap-next-button">Add ${f.title} to the Studio Archive →</button></div>`;
 }
 return `<div class="wrapmoment wraptone-${tone.id}"><div class="wrap-light wrap-light-a"></div><div class="wrap-light wrap-light-b"></div><div class="wrap-cinema">${filmWrapProgress(step)}${chapter}</div></div>`;
}

function legacyReportHTML(f){
 const l=ensureLegacyState(f);if(!l.built)buildFilmLegacy(f,{});
 return `<div class="section-title"><h2>Final run report</h2><span class="pill ${filmLegacyBadgeClass(l)}">${l.outcome}</span></div><div class="card"><div class="body">${l.summary}</div>${l.tags.length?`<div style="margin-top:9px">${l.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div>`:''}<div class="grid cols4" style="margin-top:12px"><div><strong>${money(l.opening)}</strong><div class="small">Domestic opening</div></div><div><strong>${l.peakRank?'#'+l.peakRank:'—'}</strong><div class="small">Peak rank</div></div><div><strong>${l.weeksAtOne}</strong><div class="small">Weeks #1</div></div><div><strong>${Math.round(l.roi*100)}%</strong><div class="small">Film ROI</div></div></div></div>`;
}
function wrapUI(f){
 const dom=f.weeklyResults.reduce((a,w)=>a+w.dom,0),intl=f.weeklyResults.reduce((a,w)=>a+w.intl,0),profit=f.studioRevenue-f.investment;
 const l=ensureLegacyState(f);if(!l.built)buildFilmLegacy(f,{});
 return `<div class="hero"><div class="badge">Theatrical run complete</div><div class="quote" style="margin-top:8px">${l.outcome}</div></div>
 ${legacyReportHTML(f)}
 <div class="grid cols4" style="margin-top:12px"><div class="card"><div class="badge">Domestic</div><div class="kpi">${money(dom)}</div></div><div class="card"><div class="badge">International</div><div class="kpi">${money(intl)}</div></div><div class="card"><div class="badge">Worldwide</div><div class="kpi">${money(f.finalGross)}</div></div><div class="card"><div class="badge">Studio P/L</div><div class="kpi">${profit>=0?'+':''}${money(profit)}</div></div></div>
 <div class="section-title"><h2>Reception</h2></div><div class="card"><div class="listrow"><span>Critics</span><strong>${f.review.critics}%</strong></div><div class="listrow"><span>Audience</span><strong>${f.review.audience}%</strong></div><div class="listrow"><span>Studio investment</span><strong>${money(f.investment)}</strong></div>${f.backendPaid?`<div class="listrow"><span>Talent backend paid</span><strong>${money(f.backendPaid)}</strong></div>`:''}</div>
 ${filmOutcomeFactorsHTML(f)}\n  <div class="section-title"><h2>Career consequences</h2></div><div class="card body">${careerConsequenceText(f,profit)}</div>
 ${franchiseRightsPanel(f)}
 ${typeof streamingRightsPanel==='function'?streamingRightsPanel(f):''}
 ${(()=>{const a=ensureAfterlifeState(f),season=awardsSeasonId(state.week),sameSeason=awardsSeasonId(f.completeWeek||state.week)===season,nom=awardsNominationRecord(season),nominated=(a.nominations||[]).some(x=>x.season===season),canCampaign=sameSeason&&state.lastAwardsSeasonResolved<season&&(!nom||nominated),focused=+(awardsPushCost(f,1)*(1-awardsCampaignDiscount())).toFixed(2),full=+(awardsPushCost(f,2)*(1-awardsCampaignDiscount())).toFixed(2);return `<div class="section-title"><h2>Afterlife & awards</h2><span class="pill">${awardsSummaryForFilm(f)}</span></div><div class="card"><div class="listrow"><span>Post-theatrical revenue</span><strong>${money(a.totalRevenue)}</strong></div><div class="listrow"><span>Current weekly library revenue</span><strong>${money(a.weeklyRevenue)}</strong></div><div class="listrow"><span>Library value</span><strong>${money(a.libraryValue)}</strong></div><div class="listrow"><span>Catalogue status</span><strong>${a.cultStatus?'Cult / long-tail title':'Standard catalogue'}</strong></div>${a.licensingDeals.length?`<div class="small" style="margin-top:7px">${a.licensingDeals.length} licensing deal${a.licensingDeals.length===1?'':'s'} completed.</div>`:''}${!a.awardsPush&&canCampaign?`<div class="awards-campaign-options"><button class="btn" id="awardsPushFocused"><strong>Focused campaign · ${money(focused)}</strong><span>Meaningful support with disciplined spend.</span></button><button class="btn primary" id="awardsPushFull"><strong>Full campaign · ${money(full)}</strong><span>Maximum awards push and the largest financial commitment.</span></button></div>`:a.awardsPush?`<div class="small" style="margin-top:8px">${a.awardsPushLevel===2?'Full-scale':'Focused'} awards campaign active · ${money(a.awardsPushCost)} committed.</div>`:nom&&sameSeason&&!nominated?`<div class="small" style="margin-top:8px">The Year ${season} nominations are locked and this film is outside the final field.</div>`:''}</div>`})()}
 <div class="card" style="margin-top:10px"><div class="small">Film P/L excludes weekly corporate overhead. Catalogue receipts decay over time and are separate from the film’s recorded production/release P/L.</div></div>`;
}
function careerConsequenceText(f,profit){
 const names=packageActors(f).map(t=>t.name),d=talentById(f.directorId);
 let t=`${d.name}'s reputation ${f.review.critics>=78?'improves after strong reviews':'changes only modestly'}. `;
 if(f.review.audience>=82)t+=`${names.join(' and ')} leave the film with stronger momentum. `;
 if(profit<0)t+='The loss reduces your immediate flexibility for the next slate. ';
 else if(profit>15)t+='The film gives the studio substantially more room to finance ambitious future projects.';
 return t;
}
function releaseScreen(){
 const tab=state.uiReleaseTab||'box',chart=currentBoxChart(),upcoming=state.films.filter(f=>f.releaseWeek&&f.releaseWeek>=state.week&&f.releaseWeek<=state.week+12&&f.stage!=='complete').sort((a,b)=>a.releaseWeek-b.releaseWeek);
 const playerCampaigns=playerFilms().filter(f=>['marketing','scheduled'].includes(f.stage)),inTheatres=playerFilms().filter(f=>f.stage==='cinema'),inProgress=playerFilms().map(f=>({f,row:filmRowAtWorldWeek(f,state.week)})).filter(x=>x.row&&!x.row.settledRank);
 const tabs=sectionTabs([['box','Box Office'],['theatres','In Theatres',inTheatres.length],['calendar','Calendar'],['campaigns','Campaigns',playerCampaigns.length]],tab,'data-release-tab');
 let body='';
 if(tab==='calendar'){
  body=`<div class="section-title"><h2>Release calendar</h2><span class="small">Next 12 weeks</span></div><div class="grid">${upcoming.length?upcoming.map(f=>{const d=f.directorId?talentById(f.directorId):null,lead=f.cast?.length?talentById(f.cast[0]):null;return `<div class="card click ${f.owner==='player'?'goodline':''}" ${f.owner==='player'?`data-film="${f.id}"`:`data-industry-film="${f.id}"`}><div class="film-card-layout">${filmKeyArtHTML(f,'thumb')}<div class="film-card-copy"><div class="row"><div><strong>${f.title}</strong><div class="small">${f.studio||state.studio.name} · ${f.genre}</div></div><span class="pill">${typeof releaseDayForWeek==='function'?calendarShortDate(releaseDayForWeek(f.releaseWeek)):'W'+f.releaseWeek}</span></div><div class="small" style="margin-top:7px">${d?d.name+' directing':''}${d&&lead?' · ':''}${lead?lead.name+' starring':''}</div>${aiReleasePlanHTML(f)}</div></div></div>`}).join(''):`<div class="card body">No films are currently dated in the next twelve weeks.</div>`}</div>`;
 }else if(tab==='campaigns'){
  body=`<div class="section-title"><h2>Your campaigns</h2><span class="small">Marketing and dated films before opening weekend</span></div><div class="grid cols2">${playerCampaigns.length?playerCampaigns.map(f=>{const ms=f.marketingState?marketingPublicStatus(f):null;return `<div class="card click ${f.marketingState?.pending?'attention':''}" data-film="${f.id}"><div class="film-card-layout">${filmKeyArtHTML(f,'thumb')}<div class="film-card-copy"><div class="row"><div><strong>${f.title}</strong><div class="small">${fmtStage(f.stage)}${f.releaseWeek?' · '+calendarShortDate(releaseDayForWeek(f.releaseWeek)):''}</div></div>${stagePill(f)}</div><div class="body" style="margin-top:8px">${f.stage==='marketing'?'Campaign plan still required':f.stage==='scheduled'?`${ms?.heat||'Quiet'} campaign reach · ${ms?.pressure||'Low'} expectation pressure`:`Theatrical Week ${f.cinemaWeek}`}</div></div></div></div>`}).join(''):`<div class="card body">You have no films currently in marketing or scheduled for release.</div>`}</div>`;
 }else if(tab==='theatres'){
   body=theatricalReleaseRoomHTML(inTheatres);
  }else{
  const leader=chart[0],market=chart.reduce((a,x)=>a+x.gross,0),playerRows=chart.filter(x=>x.owner==='player');
  body=`${inProgress.length?`<div class="section-title"><h2>Current weekend in progress</h2><span class="small">Final chart settles ${calendarDateLabel(sundayForWeek(state.week))}</span></div><div class="grid cols2">${inProgress.map(({f,row})=>`<div class="card click attention" data-film="${f.id}"><div class="row"><div><strong>${f.title}</strong><div class="small">Opening tracking · ${weekendTrackingLabel(row)}</div></div><span class="pill">Counting</span></div><div class="small" style="margin-top:7px">Reviews are public; gross and rank remain provisional until the whole weekend field is settled.</div></div>`).join('')}</div>`:''}${leader?`<div class="boxoffice-leader"><div class="boxoffice-leader-art">${filmKeyArtHTML(filmById(leader.id),'mini')}<div><div class="badge">${leader.chartWeek===state.week?calendarDateLabel(sundayForWeek(leader.chartWeek)):calendarDateLabel(sundayForWeek(leader.chartWeek))} · DOMESTIC #1</div><div class="quote">${leader.title}</div><div class="small">${leader.studio} · Theatrical Week ${leader.week} ${leader.weeksAtOne>1?`· ${leader.weeksAtOne} weeks at #1`:''}</div></div></div><div><div class="kpi">${money(leader.gross)}</div><div class="small">${leader.drop===null?'Opening week':leader.drop<0?`${Math.round(Math.abs(leader.drop)*100)}% growth`:`${Math.round(leader.drop*100)}% drop`}</div></div></div>`:''}
  <div class="section-title"><h2>Weekend Box Office</h2><span class="small">${chart.length?`${money(market)} domestic across ${chart.length} releases · ${leader?.chartWeek<state.week?'latest settled weekend':'settled Sunday'}`:'No settled box office yet'}</span></div>
  ${chart.length?`<div class="boxchart">${chart.map(x=>{const max=leader?.gross||1,pct=Math.max(5,x.gross/max*100);return `<div class="boxrow ${x.owner==='player'?'yourfilm':''}"><div class="rank">${x.rank}</div><div class="boxfilm click" ${x.owner==='player'?`data-film="${x.id}"`:`data-industry-film="${x.id}"`}><div class="row"><strong>${x.title}</strong><span>${boxMovementHTML(x.change)}</span></div><div class="small">${x.studio} · Week ${x.week} · ${x.drop===null?'opening':x.drop<0?`${Math.round(Math.abs(x.drop)*100)}% growth`:`${Math.round(x.drop*100)}% drop`}</div><div class="boxbar"><span style="width:${pct}%"></span></div></div><div class="boxgross"><strong>${money(x.gross)}</strong><span>${money(x.cumulative)} WW</span></div></div>`}).join('')}</div>`:`<div class="card body">No films are currently in active theatrical release this week.</div>`}
  ${playerRows.length?`<div class="section-title"><h2>Your films in cinemas</h2></div><div class="grid cols2">${playerRows.map(x=>`<div class="card click ${x.releaseType==='bomb'?'dangerline':x.releaseType==='breakout'||x.releaseType==='sleeper'?'goodline':''}" data-film="${x.id}"><div class="row"><div><strong>${x.title}</strong><div class="small">#${x.rank} · Peak #${x.bestRank||x.rank}</div></div><strong>${money(x.cumulative)} WW</strong></div><div style="margin-top:8px"><span class="pill">${x.weeksAtOne} weeks #1</span><span class="pill">${x.releaseType}</span></div></div>`).join('')}</div>`:''}
  <div class="section-title"><h2>Market read</h2></div><div class="card body">${leader?`${leader.title} controls the current weekend, but rank movement now matters as much as the opening number. Films can grow, hold #1 for several weeks, collapse after hype, or emerge slowly as sleepers.`:'The market is waiting for a release capable of converting the open demand.'}</div>`;
 }
 return topbar('Release','The box office, campaigns and the shared release calendar')+`<main class="screen">${tabs}${body}</main>${nav()}`;
}
function boxScreen(){return releaseScreen()}
