// Project Slate UI: people

function directorBio(t){
 return `${t.tag}. ${t.careerState}. Best suited to ${t.genres.slice(0,2).join(' and ').toLowerCase()} projects.`;
}
function actorBio(t){
 return `${t.tag}. ${t.careerState}. Current industry momentum is ${t.momentum>=80?'very strong':t.momentum>=65?'positive':'mixed'}.`;
}
function talentProfile(id){
 const t=talentById(id);if(!t)return talentScreen();ensureTalentCareer(t);
 const awards=talentAwardCount(t),recent=recentGeneratedCredits(t,78),rep=agencyMarketLeverage(t);
 const stats=t.type==='Actor'?[['Acting',t.acting],['Star Power',t.star],['Momentum',t.momentum],['Production Confidence',t.reliability]]:[['Film Craft',t.craft],['Audience Reach',t.commercial],['Momentum',t.momentum],['Performance Direction',t.actorDirection]];
 return topbar(t.type,'Full career profile')+`<main class="screen">${backHead(t.name,`${t.tag} · ${money(t.fee)}`)}
 <div class="hero talenthero"><div class="talentidentity">${portraitHTML(t,'lg')}<div><div class="quote">${t.name}</div><div class="body" style="margin-top:5px">${t.type==='Actor'?actorBio(t):directorBio(t)}</div><div style="margin-top:8px"><span class="pill blue">${t.careerState}</span>${t.emerging?'<span class="pill blue">EMERGING TALENT</span>':''}${t.firstMajorBreakStudio?`<span class="pill good">First major break · ${t.firstMajorBreakStudio}</span>`:''}${t.isLegend?'<span class="pill legend-badge">LEGENDS ARCHIVE</span>':''}${t.momentumDelta?`<span class="pill ${t.momentumDelta>0?'good':'warn'}">${t.momentumDelta>0?'+':''}${t.momentumDelta} recent momentum</span>`:''}</div></div></div><div style="margin-top:12px">${watchlistButton(t)}</div></div>
 <div class="section-title"><h2>Representation</h2></div><div class="card"><div class="row"><strong>${rep.agency.name}</strong><span class="pill ${rep.standing.score>=4?'good':rep.standing.score<=-4?'bad':'blue'}">${rep.relationship}</span></div><div class="body" style="margin-top:7px">${rep.agency.focus}. The client's current negotiating position is <strong>${rep.label.toLowerCase()}</strong>; agency warmth, recent career momentum and awards now shape access and terms without revealing hidden role fit.</div>${state.agencyWindows?.[t.id]&&state.week<=state.agencyWindows[t.id].expiresWeek&&filmById(state.agencyWindows[t.id].filmId)?.stage==='development'?`<div class="small" style="margin-top:8px">Priority conversation on ${filmById(state.agencyWindows[t.id].filmId).title} until Week ${state.agencyWindows[t.id].expiresWeek}. The agency is holding the door open, but the deal still has to make sense.</div>`:''}</div>
 <div class="section-title"><h2>Current profile</h2></div><div class="grid cols2">${stats.map(x=>`<div class="card"><div class="badge">${x[0]}</div><div class="kpi">${Math.round(x[1])}</div></div>`).join('')}</div>
 <div class="section-title"><h2>Momentum history</h2><span class="small">${momentumIndicator(t)}</span></div><div class="card">${t.momentumHistory?.length?t.momentumHistory.slice(0,8).map(h=>`<div class="listrow"><div><strong>${h.delta>0?'▲':h.delta<0?'▼':'→'} ${h.from} → ${h.to}</strong><div class="small">${h.reason}</div></div><span class="small">W${h.week}</span></div>`).join(''):`<div class="body">No meaningful momentum movement has been recorded yet.</div>`}</div>
 <div class="section-title"><h2>Career</h2></div><div class="card"><div class="listrow"><span>${t.isLegend?'Archive age':'Age'}</span><strong>${t.age}</strong></div><div class="listrow"><span>Status</span><strong>${t.retired?'Retired':busy(t)?'Working through Week '+t.busyUntil:'Available'}</strong></div><div class="listrow"><span>Career state</span><strong>${t.careerState}</strong></div><div class="listrow"><span>Market fee</span><strong>${money(t.fee)}</strong></div>${t.type==='Actor'?`<div class="listrow"><span>Career peak Star Power</span><strong>${Math.round(t.careerPeakStar||t.star)}</strong></div>`:''}<div class="listrow"><span>Career peak Momentum</span><strong>${Math.round(t.careerPeakMomentum||t.momentum)}</strong></div><div class="listrow"><span>Awards record</span><strong>${awards.wins} wins · ${awards.noms} nominations</strong></div><div class="listrow"><span>Relationship with your studio</span><strong>${relationshipLabel(t.relationship||0)} · ${t.relationship||0}</strong></div></div>
 ${talentRelationshipRecent(t).length?`<div class="section-title"><h2>Your studio relationship</h2><span class="small">Why the relationship moved</span></div><div class="card">${talentRelationshipRecent(t).map(h=>`<div class="listrow"><div><strong class="${h.delta>0?'goodtext':'badtext'}">${h.delta>0?'+':''}${h.delta} · ${h.reason}</strong>${h.filmId&&filmById(h.filmId)?`<div class="small">${filmById(h.filmId).title}</div>`:''}</div><span class="small">${h.day?calendarShortDate(h.day):'W'+h.week}</span></div>`).join('')}</div>`:''}
 <div class="section-title"><h2>Known working relationships</h2><span class="small">Persistent chemistry and friction between collaborators</span></div><div class="card">${knownCollaborators(t).length?knownCollaborators(t).map(x=>`<div class="listrow"><span>${x.t.name}</span><strong>${x.score>=18?'Preferred collaborator':x.score>=0?'Positive':'Difficult'} · ${Math.abs(x.score)}</strong></div>`).join(''):`<div class="body">No strong collaboration history has emerged yet.</div>`}</div>
 ${Object.keys(t.genreCareer||{}).length?`<div class="section-title"><h2>Industry associations</h2><span class="small">Built from Project Slate credits</span></div><div class="card">${Object.entries(t.genreCareer).sort((a,b)=>(b[1].score||0)-(a[1].score||0)).slice(0,5).map(([g,x])=>`<div class="listrow"><span>${g}</span><strong>${x.credits} credit${x.credits===1?'':'s'} · ${x.strong} strong result${x.strong===1?'':'s'}</strong></div>`).join('')}${t.type==='Director'&&t.trustedBudget?`<div class="listrow"><span>Proven production scale</span><strong>${money(t.trustedBudget)}</strong></div>`:''}</div>`:''}
 ${t.careerMilestones?.length?`<div class="section-title"><h2>Career timeline</h2></div><div class="card">${t.careerMilestones.slice(0,8).map(m=>`<div class="listrow"><span>${m.label}</span><span class="small">W${m.week}</span></div>`).join('')}</div>`:''}
 ${t.isRealPerson?`<div class="section-title"><h2>Selected credits</h2></div><div class="card">${(t.realCredits||[]).map(c=>`<div class="listrow"><span>${c}</span></div>`).join('')}<div class="small" style="margin-top:8px">Private roster reference. Portrait is loaded from Wikipedia/Wikimedia when available. All game ratings and simulated outcomes are fictional.</div></div>`:''}
 <div class="section-title"><h2>Project Slate career</h2><span class="small">${recent.length} credit${recent.length===1?'':'s'} in the last 78 weeks</span></div><div class="card">${t.credits.length?t.credits.slice(0,10).map(c=>`<div class="listrow"><div><strong>${typeof c==='string'?c:c.title||'Generated credit'}</strong>${typeof c==='object'?`<div class="small">${c.role||''}${c.character?` as ${c.character}`:''} · ${money(c.gross||0)} WW · ${c.critics||0}% critics</div>`:''}</div><span class="small">${typeof c==='object'&&c.week?'W'+c.week:''}</span></div>`).join(''):`<div class="body">No credits have been generated yet in this Project Slate career.</div>`}</div>
 </main>${nav()}`;
}
function peopleDirectory(){
 const q=(state.uiPeopleSearch||'').toLowerCase(),filter=state.uiPeopleFilter||'all';
 if(filter==='agencies')return `<div class="filterbar"><select id="peopleFilter" class="select"><option value="all">All people</option><option value="agencies" selected>Agencies</option></select></div><div class="section-title"><h2>Representation</h2><span class="small">${AGENCIES.length} agencies · standing is earned through client relationships</span></div><div class="grid cols2">${AGENCIES.map(a=>{const x=agencySnapshot(a),st=x.standing,clients=x.clients,hot=x.hot,market=hot?agencyMarketLeverage(hot):null;return `<div class="card ${st.score<=-4?'dangerline':st.score>=4?'goodline':''}"><div class="row"><div><div class="badge">${a.style}</div><h2 style="margin:6px 0 0">${a.name}</h2></div><span class="pill ${st.score>=4?'good':st.score<=-4?'bad':'blue'}">${st.label}</span></div><div class="body" style="margin-top:7px">${a.focus}</div><div class="small" style="margin-top:8px">${clients.length} active clients · ${st.warm} warm · ${st.cold} strained</div><div class="small">${x.windows.length} active priority conversation${x.windows.length===1?'':'s'} with your studio</div>${hot?`<div class="listrow" style="margin-top:7px"><span>Hottest client market</span><strong>${hot.name} · ${market.label}</strong></div>`:''}${x.thread?`<div class="small" style="margin-top:8px"><strong>Active thread:</strong> ${x.thread.title}</div>`:''}<div class="hr"></div>${clients.slice(0,8).map(t=>`<button class="btn ghost" data-talent="${t.id}">${t.name}</button>`).join('')}</div>`}).join('')}</div>`;
 const talent=state.talent.filter(t=>!t.retired&&(filter==='all'||(filter==='actors'&&t.type==='Actor')||(filter==='directors'&&t.type==='Director')||(filter==='legends'&&t.isLegend)||(filter==='watchlist'&&state.talentWatchlist?.includes(t.id)))&&(!q||`${t.name} ${t.tag} ${t.genres.join(' ')}`.toLowerCase().includes(q)));
 const writers=(filter==='all'||filter==='writers')?state.writers.filter(w=>!q||`${w.name} ${w.tag} ${w.genres.join(' ')}`.toLowerCase().includes(q)):[];
 return `<div class="filterbar"><input id="peopleSearch" class="search" placeholder="Search actors, directors and writers" value="${state.uiPeopleSearch||''}"><select id="peopleFilter" class="select"><option value="all" ${filter==='all'?'selected':''}>All people</option><option value="actors" ${filter==='actors'?'selected':''}>Actors</option><option value="directors" ${filter==='directors'?'selected':''}>Directors</option><option value="legends" ${filter==='legends'?'selected':''}>✦ Legends</option><option value="watchlist" ${filter==='watchlist'?'selected':''}>★ Watchlist</option><option value="writers" ${filter==='writers'?'selected':''}>Writers</option><option value="agencies">Agencies</option></select></div>
 <div class="section-title"><h2>People database</h2><span class="small">${talent.length+writers.length} shown</span></div>
 <div class="grid cols2">${talent.map(t=>{ensureTalentCareer(t);return `<div class="card click" data-talent="${t.id}"><div class="talenthead"><div class="talentidentity">${portraitHTML(t,'sm')}<div><strong>${t.name}</strong><div class="small">${t.type} · ${t.careerState}</div></div></div><strong>${money(t.fee)}</strong></div><div style="margin-top:8px">${t.type==='Actor'?`<span class="pill">Acting ${Math.round(t.acting)}</span><span class="pill">Star Power ${Math.round(t.star)}</span><span class="pill ${t.momentum>=85?'good':''}">Momentum ${momentumIndicator(t)}</span>`:`<span class="pill">Craft ${Math.round(t.craft)}</span><span class="pill">Commercial ${Math.round(t.commercial)}</span><span class="pill ${t.momentum>=85?'good':''}">Momentum ${momentumIndicator(t)}</span>`}${t.isLegend?'<span class="pill legend-badge">LEGEND</span>':''}${state.talentWatchlist?.includes(t.id)?'<span class="pill blue">Watching</span>':''}${busy(t)?`<span class="pill bad">Busy to W${t.busyUntil}</span>`:'<span class="pill good">Available</span>'}</div></div>`}).join('')}
 ${writers.map(w=>`<div class="card click" data-writer-profile="${w.id}"><div class="row"><div><strong>${w.name}</strong><div class="small">Writer · ${w.tag}</div></div><strong>${money(w.fee)}</strong></div><div style="margin-top:8px"><span class="pill">Structure ${w.structure}</span><span class="pill">Character ${w.character}</span><span class="pill">Dialogue ${w.dialogue}</span><span class="pill">Commercial ${w.commercial}</span></div><div class="small" style="margin-top:7px">${w.genres.join(' · ')}</div></div>`).join('')}</div>`;
}
function talentScreen(){return topbar('Industry','People database')+`<main class="screen">${peopleDirectory()}</main>${nav()}`}
