// Project Slate UI: industry

function aiFilmResultLabel(f){
 if(f.stage!=='complete')return 'Not yet complete';
 const p=f.estimatedProfit||0;
 if(p>15)return 'Major profit';
 if(p>3)return 'Profit';
 if(p>.5)return 'Minor profit';
 if(p>-.5)return 'Around break-even';
 if(p>-4)return 'Minor loss';
 if(p>-15)return 'Loss';
 return 'Major loss';
}
function rivalPerformance(r){
 const films=state.films.filter(f=>f.owner===r.id),done=films.filter(f=>f.stage==='complete');
 const pnl=done.reduce((a,f)=>a+(f.estimatedProfit||0),0),gross=done.reduce((a,f)=>a+(f.finalGross||0),0);
 const wins=done.filter(f=>(f.estimatedProfit||0)>.5).length,losses=done.filter(f=>(f.estimatedProfit||0)<-.5).length;
 const last3=[...done].sort((a,b)=>(b.completeWeek||b.releaseWeek||0)-(a.completeWeek||a.releaseWeek||0)).slice(0,3);
 const recent=last3.reduce((a,f)=>a+(f.estimatedProfit||0),0);
 const status=aiFinancialHealth(r),creative=done.length?done.filter(f=>f.review).reduce((a,f)=>a+(f.review?.critics||60),0)/done.filter(f=>f.review).length:60;
 const treasury=aiTreasurySnapshot(r);
 return {films,done,pnl,gross,wins,losses,status,recent,creative,debt:r.debt||0,cash:r.cash||0,reserve:treasury.reserve,available:treasury.available};
}
function rivalProfile(id){
 const r=rivalById(id),p=rivalPerformance(r),recent=[...p.done].sort((a,b)=>(b.releaseWeek||0)-(a.releaseWeek||0)).slice(0,6),active=p.films.filter(f=>f.stage!=='complete'),sig=rivalSignature(r),genreCounts={};p.done.forEach(f=>genreCounts[f.genre]=(genreCounts[f.genre]||0)+1);const fav=Object.entries(genreCounts).sort((a,b)=>b[1]-a[1])[0];
 return topbar('Studio Profile',r.name)+`<main class="screen">${backHead('Studio Profile',sig.label)}
 <div class="studio-brand-hero rival-brand-hero" style="--brand:${brandTheme(rivalBrand(r)).accent};--brand2:${brandTheme(rivalBrand(r)).accent2};--branddark:${brandTheme(rivalBrand(r)).dark}"><div>${studioLogoHTML(r.name,rivalBrand(r),'lg',true)}<div class="badge" style="margin-top:12px">${sig.label}</div><div class="quote" style="margin-top:7px">${sig.philosophy}</div></div><div class="body rival-head-copy" style="max-width:420px"><div class="rival-headline"><span class="rival-head-monogram">${r.head.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}</span><div><strong>${r.head.name}</strong><div class="small">${r.head.title} · ${r.head.personality}</div></div></div><div class="small" style="margin-top:8px">${r.head.bio}</div><div class="small" style="margin-top:9px"><strong>Current tone with your studio:</strong> ${rivalDisposition(r)}.</div><div class="small" style="margin-top:9px"><strong>Distribution tendency:</strong> ${sig.distribution}${fav?` · Most-produced genre: ${fav[0]}`:''}</div></div></div>
 <div class="grid cols4" style="margin-top:12px"><div class="card"><div class="badge">Trade estimate</div><div class="kpi">${p.status}</div></div><div class="card"><div class="badge">Completed films</div><div class="kpi">${p.done.length}</div></div><div class="card"><div class="badge">Estimated film P/L</div><div class="kpi" style="font-size:17px">${moneyRange(p.pnl)}</div></div><div class="card"><div class="badge">Wins / losses</div><div class="kpi">${p.wins} / ${p.losses}</div></div></div>
 <div class="grid cols4" style="margin-top:12px"><div class="card"><div class="badge">Recent commercial form</div><div class="kpi">${p.recent>8?'Hot':p.recent<-8?'Cold':'Mixed'}</div></div><div class="card"><div class="badge">Creative reputation</div><div class="kpi">${Math.round(p.creative)}</div></div><div class="card"><div class="badge">Debt pressure</div><div class="kpi">${p.debt>25?'High':p.debt>8?'Moderate':'Low'}</div></div><div class="card"><div class="badge">Liquidity</div><div class="kpi">${p.available>25?'Deep':p.available>10?'Healthy':p.available>2?'Tight':'Restricted'}</div></div></div>
 ${rivalryProfileHTML(r)}
 <div class="section-title"><h2>Current slate</h2></div><div class="grid">${active.length?active.map(f=>`<div class="card click" data-industry-film="${f.id}"><div class="film-card-layout">${filmKeyArtHTML(f,'thumb')}<div class="film-card-copy"><div class="row"><div><strong>${f.title}</strong><div class="small">${f.genre} · ${fmtStage(f.stage)}</div></div>${f.releaseWeek?`<span class="pill">${typeof releaseDayForWeek==='function'?calendarShortDate(releaseDayForWeek(f.releaseWeek)):'W'+f.releaseWeek}</span>`:''}</div>${f.releaseWeek?`<div class="small" style="margin-top:6px">${distributionLabel(f)}</div>`:''}</div></div></div>`).join(''):`<div class="card body">No active projects.</div>`}</div>
 <div class="section-title"><h2>Recent releases</h2></div><div class="grid">${recent.length?recent.map(f=>`<div class="card click ${f.estimatedProfit>3?'goodline':f.estimatedProfit<-4?'dangerline':''}" data-industry-film="${f.id}"><div class="film-card-layout">${filmKeyArtHTML(f,'thumb')}<div class="film-card-copy"><div class="row"><div><strong>${f.title}</strong><div class="small">${money(f.finalGross)} WW · ${aiFilmResultLabel(f)}</div></div><strong style="font-size:12px">${moneyRange(f.estimatedProfit||0)}</strong></div></div></div></div>`).join(''):`<div class="card body">No completed films yet.</div>`}</div>
 </main>${nav()}`;
}
function industryFilmProfile(id){
 const f=filmById(id),d=f.directorId?talentById(f.directorId):null,cast=(f.cast||[]).map(talentById).filter(Boolean),done=f.stage==='complete',gross=f.finalGross||f.weeklyResults?.reduce((a,w)=>a+w.dom+w.intl,0)||0;
 const profit=f.owner==='player'?(f.studioRevenue-f.investment):(f.estimatedProfit||0);
 return topbar('Industry Film',f.studio||state.studio.name)+`<main class="screen">${backHead('Industry Film',`${f.genre} · ${fmtStage(f.stage)}`)}
 ${filmIdentityHero(f)}
 ${f.ipParentId||f.ip?.installment>1?`<div class="section-title"><h2>Franchise position</h2></div><div class="card"><div class="listrow"><span>Property</span><strong>${ensureIPAsset(f).franchiseName}</strong></div><div class="listrow"><span>Entry</span><strong>${f.franchiseMode?franchiseModeLabel(f.franchiseMode):'Sequel'}</strong></div><div class="listrow"><span>Property status</span><strong>${franchiseStatus(f).label}</strong></div></div>`:''}<div class="section-title"><h2>Package</h2></div><div class="card"><div class="listrow"><span>Director</span><strong>${d?d.name:'Unknown'}</strong></div>${typeof ensureFilmRoles==='function'?rolePackageSummary(f).filter(x=>x.talent).map(x=>`<div class="listrow"><span>${x.role.name}</span><strong>${x.talent.name}</strong></div>`).join(''):`<div class="listrow"><span>Principal cast</span><strong>${cast.length?cast.map(x=>x.name).join(', '):'Unknown'}</strong></div>`}<div class="listrow"><span>Production budget</span><strong>~${money(f.budget||0)}</strong></div>${f.releaseWeek||f.stage==='complete'?`<div class="listrow"><span>Distribution</span><strong>${distributionLabel(f)}</strong></div>`:''}${f.aiMarketing!==undefined?`<div class="listrow"><span>Estimated marketing</span><strong>~${money(f.aiMarketing)}</strong></div>`:''}</div>
 ${f.review?`<div class="section-title"><h2>Reception</h2></div><div class="grid cols2"><div class="card"><div class="badge">Critics</div><div class="kpi">${f.review.critics}%</div></div><div class="card"><div class="badge">Audience</div><div class="kpi">${f.review.audience}%</div></div></div>`:''}
 <div class="section-title"><h2>Commercial result</h2></div><div class="grid cols3"><div class="card"><div class="badge">Worldwide</div><div class="kpi">${gross?money(gross):'—'}</div></div><div class="card"><div class="badge">Estimated investment</div><div class="kpi">${money(f.investment||0)}</div></div><div class="card"><div class="badge">Estimated studio P/L</div><div class="kpi">${done?`${profit>=0?'+':''}${money(profit)}`:'Pending'}</div></div></div>
 ${done?`<div class="card ${profit>3?'goodline':profit<-4?'dangerline':''}" style="margin-top:12px"><div class="body"><strong>${f.owner==='player'?(profit>3?'Profit':profit<-4?'Loss':'Around break-even'):aiFilmResultLabel(f)}.</strong> ${f.owner==='player'?'Your recorded studio revenue':'Trade estimates put studio theatrical/post-theatrical revenue'} at roughly ${money(f.studioRevenue||0)} against ${money(f.investment||0)} invested.</div></div>`:''}
 </main>${nav()}`;
}
function industryRecords(){
 const done=state.films.filter(f=>f.stage==='complete'&&f.finalGross>0);
 if(!done.length)return `<div class="card body">The industry is too young to have meaningful records yet.</div>`;
 const biggest=[...done].sort((a,b)=>b.finalGross-a.finalGross)[0];
 const bestReview=[...done].filter(f=>f.review).sort((a,b)=>b.review.critics-a.review.critics)[0];
 const profits=done.map(f=>({f,p:f.owner==='player'?(f.studioRevenue-f.investment):(f.estimatedProfit||0)}));
 const best=[...profits].sort((a,b)=>b.p-a.p)[0],worst=[...profits].sort((a,b)=>a.p-b.p)[0];
 const actors=state.talent.filter(t=>t.type==='Actor'&&!t.retired),directors=state.talent.filter(t=>t.type==='Director'&&!t.retired);
 const topStar=[...actors].sort((a,b)=>(b.star||0)-(a.star||0))[0],hot=[...actors].sort((a,b)=>(b.momentum||0)-(a.momentum||0))[0],hotDir=[...directors].sort((a,b)=>(b.momentum||0)-(a.momentum||0))[0];
 const awardPeople=state.talent.map(t=>({t,a:talentAwardCount(t)})).sort((x,y)=>y.a.wins-x.a.wins||y.a.noms-x.a.noms)[0];
 return `<div class="grid cols2"><div class="card click" data-industry-film="${biggest.id}"><div class="badge">Biggest worldwide gross</div><div class="kpi">${money(biggest.finalGross)}</div><div class="small">${biggest.title}</div></div>${bestReview?`<div class="card click" data-industry-film="${bestReview.id}"><div class="badge">Highest critic score</div><div class="kpi">${bestReview.review.critics}%</div><div class="small">${bestReview.title}</div></div>`:''}<div class="card click" data-industry-film="${best.f.id}"><div class="badge">Best estimated studio result</div><div class="kpi" style="font-size:16px">${best.f.owner==='player'?`${best.p>=0?'+':''}${money(best.p)}`:moneyRange(best.p)}</div><div class="small">${best.f.title}</div></div><div class="card click" data-industry-film="${worst.f.id}"><div class="badge">Biggest estimated loss</div><div class="kpi" style="font-size:16px">${worst.f.owner==='player'?`${worst.p>=0?'+':''}${money(worst.p)}`:moneyRange(worst.p)}</div><div class="small">${worst.f.title}</div></div>
 ${topStar?`<div class="card click" data-talent="${topStar.id}"><div class="badge">Highest Star Power</div><div class="talentidentity" style="margin-top:8px">${portraitHTML(topStar,'xs')}<div><div class="kpi">${Math.round(topStar.star)}</div><div class="small">${topStar.name}</div></div></div></div>`:''}
 ${hot?`<div class="card click" data-talent="${hot.id}"><div class="badge">Hottest actor</div><div class="talentidentity" style="margin-top:8px">${portraitHTML(hot,'xs')}<div><div class="kpi">${Math.round(hot.momentum||60)}</div><div class="small">${hot.name}</div></div></div></div>`:''}
 ${hotDir?`<div class="card click" data-talent="${hotDir.id}"><div class="badge">Hottest director</div><div class="talentidentity" style="margin-top:8px">${portraitHTML(hotDir,'xs')}<div><div class="kpi">${Math.round(hotDir.momentum||60)}</div><div class="small">${hotDir.name}</div></div></div></div>`:''}
 ${awardPeople?.a?.wins?`<div class="card click" data-talent="${awardPeople.t.id}"><div class="badge">Most awarded filmmaker / performer</div><div class="kpi">${awardPeople.a.wins}</div><div class="small">${awardPeople.t.name}</div></div>`:''}
 </div>
 ${state.yearbooks?.length?`<div class="section-title"><h2>Industry yearbooks</h2><span class="small">A permanent record of each 52-week year</span></div><div class="grid">${state.yearbooks.map(y=>`<div class="card"><div class="row"><strong>Year ${y.year} · ${y.era||'Industry yearbook'}</strong><span class="small">through W${y.week}</span></div>${y.biggestGross?`<div class="listrow"><span>Box-office leader</span><strong>${y.biggestGross.title} · ${money(y.biggestGross.value)}</strong></div>`:''}${y.bestReviewed?`<div class="listrow"><span>Critics' favourite</span><strong>${y.bestReviewed.title} · ${y.bestReviewed.value}%</strong></div>`:''}${y.bestResult?`<div class="listrow"><span>Best studio result</span><strong>${y.bestResult.title} · ${y.bestResult.value>=0?'+':''}${money(y.bestResult.value)}</strong></div>`:''}${y.playerHeadline?`<div class="listrow"><span>Your headline film</span><strong>${y.playerHeadline.title}${y.playerHeadline.critics?` · ${y.playerHeadline.critics}% critics`:y.playerHeadline.gross?` · ${money(y.playerHeadline.gross)}`:''}</strong></div>`:''}${y.hotActor?`<div class="listrow"><span>Hottest actor</span><strong>${y.hotActor.name} · ${Math.round(y.hotActor.momentum)}</strong></div>`:''}${y.hotDirector?`<div class="listrow"><span>Hottest director</span><strong>${y.hotDirector.name} · ${Math.round(y.hotDirector.momentum)}</strong></div>`:''}</div>`).join('')}</div>`:''}`;
}

function industryTrendsBody(){
 ensureAudienceMarket();const genreCards=genres.map(g=>({g,...genreMarketLabel(g)})),mood=industryMoodSnapshot();
 return `<div class="hero"><div class="badge">INDUSTRY MOOD · CURRENT QUARTER</div><div class="quote" style="margin-top:8px">${mood.label}</div><div class="body" style="margin-top:8px">${mood.summary}</div><div class="small" style="margin-top:7px">This is a trade read of the living simulation, not a hidden global buff. Financing, talent, audience response and crowding are being summarized from conditions already in the market.</div></div>
 ${industryMoodPanel(mood)}
 <div class="section-title"><h2>Audience appetites</h2></div><div class="grid cols2">${SEGMENT_KEYS.map(segment=>{const interests=segmentCurrentInterests(segment),top=interests.slice(0,2),low=interests.at(-1);return `<div class="card"><strong>${segment}</strong><div class="small" style="margin-top:7px">Most receptive to <strong>${top.map(x=>x.genre).join(' / ')}</strong>.</div><div class="small" style="margin-top:5px">Cooler on ${low.genre} right now.</div></div>`}).join('')}</div>
 <div class="section-title"><h2>Genre market</h2><span class="small">Hits create heat; imitation can create crowding</span></div><div class="grid cols2">${genreCards.map(x=>`<div class="card ${x.cls==='good'?'goodline':x.cls==='bad'?'dangerline':''}"><div class="row"><strong>${x.g}</strong><span class="pill ${x.cls}">${x.label}</span></div><div class="small" style="margin-top:7px">${x.text}</div></div>`).join('')}</div>
 <div class="section-title"><h2>Your studio's audience equity</h2></div><div class="grid cols2">${SEGMENT_KEYS.map(k=>{const v=ensureAudienceMarket().affinity[k]||0;return `<div class="card"><div class="row"><strong>${k}</strong><span class="pill ${v>=5?'good':v<=-3?'warn':''}">${audienceAffinityLabel(v)}</span></div></div>`}).join('')}</div>`;
}

function awardsIndustryBody(){
 const current=awardsCurrentSeason(),archive=state.awardsArchive||[],nom=current.nominations,nominationWeek=(current.season-1)*52+50,ceremonyWeek=current.end,eligible=current.films.filter(f=>f.review?.critics>=60||f.creative?.positioning==='prestige'||f.review?.audience>=82).sort((a,b)=>awardsEligibilityScore(b,'picture')-awardsEligibilityScore(a,'picture')).slice(0,10);
 return `<div class="section-title"><h2>Year ${current.season} awards race</h2><span class="small">${nom?'Nominations locked':`Nominations W${nominationWeek} · ceremony W${ceremonyWeek}`}</span></div>
 ${nom?`<div class="grid cols2">${nom.categories.map(cat=>`<div class="card"><div class="awardlabel">${cat.label}</div><div class="nominees">${cat.nominees.length?cat.nominees.map(n=>`<div>${n.subject}<span>${n.studio}</span></div>`).join(''):'<div>No nominees</div>'}</div></div>`).join('')}</div>`:eligible.length?`<div class="grid cols2">${eligible.map(f=>{const a=ensureAfterlifeState(f),buzz=awardBuzzLabel(awardsEligibilityScore(f,'picture'));return `<div class="card click" ${f.owner==='player'?`data-film="${f.id}"`:`data-industry-film="${f.id}"`}><div class="row"><div><strong>${f.title}</strong><div class="small">${f.studio||state.studio.name} · ${f.genre}</div></div>${a.awardsPush?'<span class="pill blue">Campaigning</span>':''}</div><div class="small" style="margin-top:7px">${buzz.label} for Picture · Critics ${f.review?.critics||'—'}% · Audience ${f.review?.audience||'—'}%</div></div>`}).join('')}</div>`:`<div class="card body">No serious awards contenders have emerged yet this year.</div>`}
 <div class="section-title"><h2>Past ceremonies</h2><span class="small">Completed seasons move here after Awards Night</span></div><div class="grid awards-history-list">${archive.length?archive.map(c=>`<div class="card awards-history-card"><div class="awards-history-head"><strong>Year ${c.season}</strong><span class="pill">${c.playerWins} studio wins</span></div><div class="awards-history-winners">${c.categories.map(cat=>{const w=cat.nominees.find(n=>n.filmId===cat.winnerId);return `<div class="awards-history-row"><span>${cat.label}</span><strong>${w?.subject||'—'}</strong></div>`}).join('')}</div></div>`).join(''):`<div class="card body">No completed awards ceremonies yet.</div>`}</div>`;
}
function industryScreen(){
 const tab=state.industryTab||'news';
 const hot=state.talent.filter(t=>!t.retired).sort((a,b)=>(b.momentum||60)-(a.momentum||60)).slice(0,5);
 const important=state.news.filter(n=>['Press Release','Box Office Alert','Trade Report','Talent Watch','Your Studio','Studio Finance','Industry Alert'].includes(n.kind)).slice(0,10);
 const tabs=sectionTabs([['news','News'],['studios','Studios'],['people','People'],['trends','Trends'],['awards','Awards'],['records','Records']],tab,'data-industry-tab');
 let body='';
 if(tab==='studios'){
  const table=studioStandings();
  body=`<div class="section-title"><h2>Studio table</h2><span class="small">Recognition, audience following, awards and recent commercial form</span></div><div class="card">${table.map(s=>{const b=s.player?ensurePlayerBrand():rivalBrand(rivalById(s.id));return `<div class="listrow ${s.player?'goodline click':''}" ${s.player?'data-nav="studio"':`data-rival="${s.id}"`}><div class="rank">#${s.rank}</div><div style="flex:1">${studioLogoHTML(s.name,b,'xs',true)}<div class="small" style="margin:4px 0 0 39px">${s.style} · ${studioFansLabel(s.fans)}</div></div><div style="text-align:right"><strong>${Math.round(s.recognition)}</strong><div class="small">recognition</div></div></div>`}).join('')}</div><div class="section-title"><h2>Rival detail</h2></div><div class="grid cols2">${state.rivals.map(r=>{const p=rivalPerformance(r),standing=table.find(x=>x.id===r.id);return `<div class="card click ${p.pnl<-15?'dangerline':p.pnl>20?'goodline':''}" data-rival="${r.id}"><div class="row"><div>${studioLogoHTML(r.name,rivalBrand(r),'sm',true)}<div class="small" style="margin:5px 0 0 51px">#${standing?.rank||'?'} · ${r.head?.name||'Studio leadership'} · ${rivalSignature(r).label}</div></div><span class="pill">${p.status}</span></div><div class="grid cols3" style="margin-top:10px"><div><strong>${p.done.length}</strong><div class="small">released</div></div><div><strong>${p.wins}/${p.losses}</strong><div class="small">wins/losses</div></div><div><strong>${Math.round(r.recognition||r.reputation)}</strong><div class="small">recognition</div></div></div><div class="small" style="margin-top:9px">Following ${studioFansLabel(r.fans||.5)} · Form ${p.recent>8?'hot':p.recent<-8?'cold':'mixed'} · Liquidity ${p.available>25?'deep':p.available>10?'healthy':p.available>2?'tight':'restricted'}</div></div>`}).join('')}</div>`;
 }
 else if(tab==='people')body=peopleDirectory();
 else if(tab==='trends')body=industryTrendsBody();
 else if(tab==='awards')body=awardsIndustryBody();
 else if(tab==='records')body=`<div class="section-title"><h2>Industry records</h2><span class="small">The history generated by this career</span></div>${industryRecords()}`;
 else body=`<div class="section-title"><h2>Top stories</h2><span class="small">The stories shaping the business</span></div><div class="grid">${(important.length?important:state.news.slice(0,5)).map(n=>`<div class="card click ${n.kind==='Box Office Alert'||n.kind==='Industry Alert'?'attention':n.kind==='Your Studio'?'goodline':''}" data-news-id="${n.id}"><div class="row">${pressLogoHTML(n.publication||'Screen Trade','xs',true)}<span class="small">${n.day?calendarShortDate(n.day):'W'+n.week}</span></div><div class="quote" style="font-size:16px;margin-top:8px">${n.headline}</div><div class="small" style="margin-top:7px">${n.deck}</div></div>`).join('')}</div>${pressRoomSnapshot()}<div class="section-title"><h2>Talent watch</h2><button class="btn ghost" data-industry-tab="people">Open People</button></div><div class="card">${hot.map(t=>`<div class="listrow click" data-talent="${t.id}"><div class="talentidentity">${portraitHTML(t,'xs')}<div><strong>${t.name}</strong><div class="small">${t.type} · ${t.careerState||t.tag}</div></div></div><span class="pill ${t.momentum>=88?'good':''}">Momentum ${momentumIndicator(t)}</span></div>`).join('')}</div><div class="section-title"><h2>Latest wire</h2></div><div class="grid">${state.news.slice(0,24).map(n=>`<div class="card click ${n.kind==='Your Studio'?'goodline':''}" data-news-id="${n.id}"><div class="row">${pressLogoHTML(n.publication||'Screen Trade','xs',true)}<span class="small">${n.day?calendarShortDate(n.day):'W'+n.week}</span></div><div class="body" style="margin-top:7px"><strong>${n.headline}</strong></div><div class="small" style="margin-top:6px">${newsKindLabel(n.kind)}</div></div>`).join('')}</div>`;
 return topbar('Industry','The world beyond your own slate')+`<main class="screen">${tabs}${body}</main>${nav()}`;
}
